# -*- coding: utf-8 -*-
"""Lesson registry for the LinkedIn coding video course.

Each lesson renders to its own mp4 so a pattern can be revised in 15–25 minutes.
Chapters follow the researched question distribution, not a generic syllabus:
trees and graphs dominate the LinkedIn reports, data-structure design is next,
and dynamic programming appears in none of the reports found.
"""

LESSONS = [
 # ---------------- chapter 1: how the round works ----------------
 dict(id='c1l1-how-linkedin-asks', chapter='c1', module='c1l1_howtheyask',
      title='How LinkedIn coding rounds actually work',
      file='LinkedIn-Coding-1.1-How-The-Round-Works', mins=16,
      pattern='Orientation', relevance='High', reports='Official pack + 8 candidate reports',
      latest='2026', confidence='High'),

 dict(id='c1l2-valid-parens', chapter='c1', module='c1l2_validparens',
      title='Valid Parentheses — the warm-up, and what they watch',
      file='LinkedIn-Coding-1.2-Valid-Parentheses', mins=12,
      pattern='Stacks · warm-up discipline', relevance='High',
      reports='Your list + LinkedIn tagged set', latest='2026', confidence='High'),

 # ---------------- chapter 2: trees and n-ary structures ----------------
 dict(id='c2l1-find-leaves', chapter='c2', module='c2l1_findleaves',
      title='Find Leaves of Binary Tree',
      file='LinkedIn-Coding-2.1-Find-Leaves', mins=14,
      pattern='Trees · post-order accumulation', relevance='High',
      reports='Your own list + LeetCode LinkedIn tag', latest='2026', confidence='High'),
 dict(id='c2l2-upside-down', chapter='c2', module='c2l2_upsidedown',
      title='Binary Tree Upside Down',
      file='LinkedIn-Coding-2.2-Upside-Down', mins=15,
      pattern='Trees · pointer rewiring', relevance='High',
      reports='Your own list (twice, incl. a 0/1 right-child variant)', latest='2026', confidence='High'),
 dict(id='c2l3-keyed-merge', chapter='c2', module='c2l3_keyedmerge',
      title='Merge two keyed trees, summing values',
      file='LinkedIn-Coding-2.3-Keyed-Tree-Merge', mins=16,
      pattern='N-ary trees · recursion with a combiner', relevance='High',
      reports='Your own list, with the exact wording', latest='2026', confidence='High'),
 dict(id='c2l4-nested-sum', chapter='c2', module='c2l4_nestedsum',
      title='Nested List Weight Sum II, and the compact tree',
      file='LinkedIn-Coding-2.4-Nested-And-Compact', mins=17,
      pattern='Nested structures · level accumulation', relevance='High',
      reports='Exponent 2026 phone screen + LeetCode tag + your list', latest='2026', confidence='High'),
 dict(id='c2r-recap', chapter='c2', module='c2r_recap',
      title='Chapter 2 recap — trees, templates and a mini mock',
      file='LinkedIn-Coding-2.R-Trees-Recap', mins=11,
      pattern='Recap', relevance='—', reports='—', latest='—', confidence='—'),

 # ---------------- chapter 3: graphs and BFS ----------------
 dict(id='c3l1-word-ladder', chapter='c3', module='c3l1_wordladder',
      title='Word Ladder, and why bidirectional BFS',
      file='LinkedIn-Coding-3.1-Word-Ladder', mins=18,
      pattern='Graphs · BFS on an implicit graph', relevance='High',
      reports='Your list + LeetCode Staff report (Jul 2025)', latest='2025', confidence='High'),
 dict(id='c3l2-the-maze', chapter='c3', module='c3l2_themaze',
      title='The Maze — when the edges are not the cells',
      file='LinkedIn-Coding-3.2-The-Maze', mins=15,
      pattern='Graphs · modelling the state space', relevance='High',
      reports='Your list + a 2026 AI-round maze class', latest='2026', confidence='High'),
 dict(id='c3l3-min-degree', chapter='c3', module='c3l3_mindegree',
      title='Minimum degree of connection (and return the path)',
      file='LinkedIn-Coding-3.3-Degrees-Of-Connection', mins=17,
      pattern='Bidirectional BFS · path reconstruction', relevance='High',
      reports='Your list, with the expected answer named', latest='2026', confidence='High'),
 dict(id='c3l4-build-order', chapter='c3', module='c3l4_buildorder',
      title='getBuildOrder — topological sort, cycles and parallel waves',
      file='LinkedIn-Coding-3.4-Build-Order', mins=17,
      pattern='Graphs · topological sort', relevance='High',
      reports='Blind infra report (Sep 2025) + Glassdoor', latest='2025', confidence='High'),
 dict(id='c3r-recap', chapter='c3', module='c3r_recap',
      title='Chapter 3 recap — graphs, templates and a mini mock',
      file='LinkedIn-Coding-3.R-Graphs-Recap', mins=12,
      pattern='Recap', relevance='—', reports='—', latest='—', confidence='—'),

 # ---------------- chapter 4: data structure design ----------------
 dict(id='c4l1-all-oone', chapter='c4', module='c4l1_alloone',
      title='All O`one — every operation in O(1)',
      file='LinkedIn-Coding-4.1-All-O-One', mins=18,
      pattern='Data structure design · doubly linked list of buckets', relevance='Highest',
      reports='Your list + LeetCode Staff report (Jul 2025)', latest='2026', confidence='High'),
 dict(id='c4l2-getrandom', chapter='c4', module='c4l2_getrandom',
      title='Insert Delete GetRandom O(1), duplicates allowed',
      file='LinkedIn-Coding-4.2-GetRandom-Duplicates', mins=16,
      pattern='Data structure design · array + index set', relevance='High',
      reports='Your list + a Taro Senior Infra report ("design a random set")', latest='2025', confidence='High'),
 dict(id='c4l3-word-distance', chapter='c4', module='c4l3_worddistance',
      title='Shortest Word Distance II — design for repeated queries',
      file='LinkedIn-Coding-4.3-Shortest-Word-Distance', mins=15,
      pattern='Data structure design · precomputed index + merge', relevance='High',
      reports='Your list + LinkedIn tagged set', latest='2026', confidence='High'),
 dict(id='c4l4-lfu', chapter='c4', module='c4l4_lfu',
      title='LFU Cache, and the GetRank follow-up',
      file='LinkedIn-Coding-4.4-LFU-Cache', mins=18,
      pattern='Data structure design · frequency buckets', relevance='Highest',
      reports='Taro Staff report (Jul 2025), with the ranking follow-up', latest='2025', confidence='High'),
 dict(id='c4r-recap', chapter='c4', module='c4r_recap',
      title='Chapter 4 recap — data structure design, templates and a mini mock',
      file='LinkedIn-Coding-4.R-Design-Recap', mins=12,
      pattern='Recap', relevance='—', reports='—', latest='—', confidence='—'),

 # ---------------- chapter 5: sliding window and two pointers ----------------
 dict(id='c5l1-consecutive-ones', chapter='c5', module='c5l1_consecutiveones',
      title='Max Consecutive Ones III — the window that never shrinks',
      file='LinkedIn-Coding-5.1-Max-Consecutive-Ones', mins=15,
      pattern='Sliding window', relevance='High',
      reports='Your list + LinkedIn tagged set', latest='2026', confidence='High'),
 dict(id='c5l2-palindrome', chapter='c5', module='c5l2_palindrome',
      title='Valid Palindrome II — one deletion, two pointers',
      file='LinkedIn-Coding-5.2-Valid-Palindrome', mins=13,
      pattern='Two pointers', relevance='High',
      reports='Reported with a k-edits extension', latest='2026', confidence='Medium'),
 dict(id='c5l3-triangle', chapter='c5', module='c5l3_triangle',
      title='Valid Triangle Number — sort, then collapse a loop',
      file='LinkedIn-Coding-5.3-Valid-Triangle', mins=14,
      pattern='Two pointers after sorting', relevance='High',
      reports='LinkedIn phone-screen write-up', latest='2026', confidence='Medium'),
 dict(id='c5r-recap', chapter='c5', module='c5r_recap',
      title='Chapter 5 recap — windows, pointers and a mini mock',
      file='LinkedIn-Coding-5.R-Window-Recap', mins=11,
      pattern='Recap', relevance='—', reports='—', latest='—', confidence='—'),

 # ---------------- chapter 6: hashing and prefix sums ----------------
 dict(id='c6l1-dna', chapter='c6', module='c6l1_dna',
      title='Repeated DNA Sequences — rolling hashes and when not to bother',
      file='LinkedIn-Coding-6.1-Repeated-DNA', mins=15,
      pattern='Hashing · rolling hash', relevance='High',
      reports='LinkedIn tagged set', latest='2026', confidence='Medium'),
 dict(id='c6l2-booths', chapter='c6', module='c6l2_booths',
      title='The booths problem — maximise the experience factor',
      file='LinkedIn-Coding-6.2-Booths-Experience-Factor', mins=17,
      pattern='Prefix products · range queries', relevance='High',
      reports='Your list, with the exact wording', latest='2026', confidence='High'),
 dict(id='c6r-recap', chapter='c6', module='c6r_recap',
      title='Chapter 6 recap — hashing, prefixes and a mini mock',
      file='LinkedIn-Coding-6.R-Hashing-Recap', mins=11,
      pattern='Recap', relevance='—', reports='—', latest='—', confidence='—'),

 # ---------------- chapter 7: binary search and elimination ----------------
 dict(id='c7l1-k-closest', chapter='c7', module='c7l1_kclosest',
      title='Find K Closest Elements — binary search on the answer',
      file='LinkedIn-Coding-7.1-K-Closest-Elements', mins=16,
      pattern='Binary search on a window start', relevance='High',
      reports='Your list + LinkedIn tagged set', latest='2026', confidence='High'),
 dict(id='c7l2-celebrity', chapter='c7', module='c7l2_celebrity',
      title='Find the Celebrity — elimination, and the cost of an API call',
      file='LinkedIn-Coding-7.2-Find-The-Celebrity', mins=16,
      pattern='Elimination · adversary argument', relevance='High',
      reports='Your list + a Taro DSA-round report', latest='2025', confidence='High'),
 dict(id='c7r-recap', chapter='c7', module='c7r_recap',
      title='Chapter 7 recap — search, elimination and a mini mock',
      file='LinkedIn-Coding-7.R-Elimination-Recap', mins=11,
      pattern='Recap', relevance='—', reports='—', latest='—', confidence='—'),

 # ---------------- chapter 8: backtracking and maths ----------------
 dict(id='c8l1-letters', chapter='c8', module='c8l1_letters',
      title='Letter Combinations — backtracking, and making it lazy',
      file='LinkedIn-Coding-8.1-Letter-Combinations', mins=16,
      pattern='Backtracking · generators', relevance='High',
      reports='Your list + LinkedIn tagged set', latest='2026', confidence='High'),
 dict(id='c8l2-bulbs', chapter='c8', module='c8l2_bulbs',
      title='Bulb Switcher — when the answer is one line of maths',
      file='LinkedIn-Coding-8.2-Bulb-Switcher', mins=13,
      pattern='Maths · reasoning out loud', relevance='High',
      reports='Your list', latest='2026', confidence='Medium'),
 dict(id='c8r-recap', chapter='c8', module='c8r_recap',
      title='Chapter 8 recap — search, maths and a mini mock',
      file='LinkedIn-Coding-8.R-Backtracking-Recap', mins=11,
      pattern='Recap', relevance='—', reports='—', latest='—', confidence='—'),

 # ---------------- chapter 9: concurrency and fundamentals ----------------
 dict(id='c9l1-threadsafe', chapter='c9', module='c9l1_threadsafe',
      title='"Now make it thread-safe" — the pivot that decides the round',
      file='LinkedIn-Coding-9.1-Make-It-Thread-Safe', mins=18,
      pattern='Concurrency · locking strategy', relevance='Highest',
      reports='Glassdoor phone screen (Mar 2026) + repeated as a follow-up', latest='2026', confidence='High'),
 dict(id='c9l2-fundamentals', chapter='c9', module='c9l2_fundamentals',
      title='OS and networking fundamentals they actually ask',
      file='LinkedIn-Coding-9.2-OS-And-Networking', mins=17,
      pattern='Systems fundamentals', relevance='High',
      reports='Taro Senior Infra report (Oct 2025)', latest='2025', confidence='High'),

 # ---------------- chapter 10: revision and the full mock ----------------
 dict(id='c10l1-revision', chapter='c10', module='c10l1_revision',
      title='Rapid revision — every pattern in one pass',
      file='LinkedIn-Coding-10.1-Rapid-Revision', mins=20,
      pattern='Revision', relevance='—', reports='—', latest='—', confidence='—'),
 dict(id='c10l2-mock', chapter='c10', module='c10l2_mock',
      title='The 50-minute mock, run in real time',
      file='LinkedIn-Coding-10.2-Fifty-Minute-Mock', mins=22,
      pattern='Mock interview', relevance='—', reports='—', latest='—', confidence='—'),
]

CHAPTERS = {
 'c1': dict(num=1, title='How LinkedIn coding rounds actually work',
            why='The official pack says this module is about modularity, extensibility and finding bugs — not an algorithm sprint. '
                'Start here so the rest of the course lands in the right frame.'),
 'c2': dict(num=2, title='Trees and n-ary structures',
            why='The single biggest cluster in the research: Find Leaves, Upside Down, the keyed merge, nested traversal and the '
                'compact tree all came from your own list or independent reports.'),
 'c3': dict(num=3, title='Graphs and BFS',
            why='Second biggest cluster, and the most LinkedIn-flavoured — the product is a graph. Word Ladder, The Maze, degrees '
                'of connection and build order.'),
 'c4': dict(num=4, title='Data structure design',
            why='Four reported questions sit here \u2014 All O`one, GetRandom with duplicates, Shortest Word Distance II and '
                'LFU. It is the cluster LinkedIn leans on when it wants to see you design rather than recall.'),
 'c5': dict(num=5, title='Sliding window and two pointers',
            why='The cheapest patterns to master and the easiest to fumble under pressure. Three reported questions.'),
 'c6': dict(num=6, title='Hashing and prefix sums',
            why='Where a quadratic answer quietly passes the examples and fails the real input. Includes the booths problem '
                'from your own list.'),
 'c7': dict(num=7, title='Binary search and elimination',
            why='Two reported questions that are really the same idea: throw away half the candidates with one comparison.'),
 'c8': dict(num=8, title='Backtracking and maths',
            why='Letter Combinations is on the tagged set; Bulb Switcher is the question where thinking out loud is the '
                'entire answer.'),
 'c9': dict(num=9, title='Concurrency and fundamentals',
            why='The reported pivot \u2014 "now make it thread-safe" \u2014 plus the OS and networking questions an infra '
                'interviewer asks when the coding is done early.'),
 'c10': dict(num=10, title='Rapid revision and the full mock',
            why='Every pattern in one pass, then a timed 50-minute mock run exactly as the round runs.'),
}

PLANNED = []   # all ten chapters are written
