# -*- coding: utf-8 -*-
"""Research pass 2 — 22 September 2026.

Strict classification. Something is a REPORTED question only when a candidate
described being asked it, or the reader supplied it from their own collection.
Preparation guides and "top questions" lists are GENERAL, never REPORTED.

conf:  HIGH   = several independent recent reports, or reader-supplied first-party
       MEDIUM = one strong recent report, or several older ones
       LOW    = single report, thin detail, or old
kind:  reported | general | inference
"""

DATE = '22 September 2026'
PASS = 2

# ---------------------------------------------------------------- sources
SRC = {
 'reader':   dict(name='Reader\'s own collection of past LinkedIn questions', date='22 Sep 2026', url=None,
                  kind='first-party', note='Supplied directly by the reader; the strongest signal in this file.'),
 'taro-staff': dict(name='Taro — LinkedIn Staff SWE interview experience (no offer)', date='18 Jul 2025',
                  url='https://www.jointaro.com/interviews/companies/linkedin/experiences/staff-software-engineer-sunnyvale-ca-july-18-2025-no-offer-positive-0010852f/',
                  kind='first-hand', note='Sunnyvale. Phone screen.'),
 'taro-infra': dict(name='Taro — LinkedIn Senior SWE Infrastructure (no offer)', date='1 Oct 2025',
                  url='https://www.jointaro.com/interviews/companies/linkedin/experiences/senior-software-engineer-infrastructure-united-states-october-1-2025-no-offer-negative-2cf610ee/',
                  kind='first-hand', note='United States. OS/networking fundamentals plus one coding question.'),
 'taro-india': dict(name='Taro — LinkedIn Staff Engineer, India (offer)', date='12 May 2025',
                  url='https://www.jointaro.com/interviews/companies/linkedin/experiences/staff-engineer-india-may-12-2025-accepted-offer-neutral-ca8f7d74/',
                  kind='first-hand', note='India. 3 coding + craftsmanship + 2 design + host manager.'),
 'blind-infra': dict(name='Blind — LinkedIn Senior SWE Infrastructure experience', date='30 Sep 2025',
                  url='https://www.teamblind.com/post/linkedin-senior-software-engineer-infrastructure-interview-experience-rfq58zbt',
                  kind='first-hand', note='Virtual. Two coding rounds, job scheduler design, host manager.'),
 'exp-cand':  dict(name='Exponent — LinkedIn Senior SWE (Apps) experience', date='≈ Mar 2026',
                  url='https://www.tryexponent.com/experiences/linkedin-senior-software-engineer-interview-dc48e8',
                  kind='first-hand', note='US. AI coding round on HackerRank; autosuggest design; migration influence question.'),
 'exp-bank':  dict(name='Exponent — LinkedIn system design question bank', date='read 22 Sep 2026',
                  url='https://www.tryexponent.com/questions?company=linkedin&type=system-design',
                  kind='aggregated', note='Carries relative recency labels ("asked a month ago").'),
 'lc-staff':  dict(name='LeetCode Discuss — LinkedIn Staff SWE experience (offer)', date='Jun 2025',
                  url='https://leetcode.com/discuss/post/6858262/linkedin-staff-software-engineer-intervi-mg5c/',
                  kind='first-hand', note='Read via search summaries — LeetCode blocks direct fetching.'),
 'lc-compact': dict(name='LeetCode Discuss — LinkedIn phone screen, compact tree build',
                  date='reader-supplied link', url='https://leetcode.com/discuss/post/124893/linkedin-phone-screen-compact-tree-build-lw27/',
                  kind='first-hand', note='Supplied by the reader; contains compact-tree, valid-triangle and upside-down-tree reports.'),
 'lc-tag':    dict(name='LeetCode company tag — LinkedIn, six-month list', date='2026',
                  url='https://leetcode.com/problem-list/linkedin-six-months/',
                  kind='aggregated', note='Frequency proxy, not a report. The reader\'s list overlaps it heavily.'),
 'gd-swe':    dict(name='Glassdoor — LinkedIn Software Engineer interview questions', date='2025–2026',
                  url='https://www.glassdoor.com/Interview/LinkedIn-Software-Engineer-Interview-Questions-EI_IE34865.0,8_KO9,26.htm',
                  kind='aggregated', note='Direct fetch blocked; read via search summaries.'),
 'gd-staff':  dict(name='Glassdoor — LinkedIn Staff Software Engineer interview questions', date='2025–2026',
                  url='https://www.glassdoor.com/Interview/LinkedIn-Staff-Software-Engineer-Interview-Questions-EI_IE34865.0,8_KO9,32.htm',
                  kind='aggregated', note='Direct fetch blocked; read via search summaries.'),
 'hi-ai':     dict(name='Hello Interview — LinkedIn\'s AI-enabled coding interview', date='20 Feb 2026',
                  url='https://www.hellointerview.com/blog/linkedin-ai-enabled-coding',
                  kind='guide-on-reports', note='Written from candidate reports; names specific problems.'),
 'hi-fmt':    dict(name='Hello Interview — AI-enabled interview formats', date='2026',
                  url='https://www.hellointerview.com/learn/ai-coding/overview/interview-formats', kind='guide-on-reports', note=''),
 'cond':      dict(name='Coditioning — LinkedIn SWE AI-enabled coding', date='25 Jun 2026',
                  url='https://www.coditioning.com/blog/1406/linkedin-swe-ai-enabled-coding', kind='guide-on-reports', note=''),
 'blind-fe':  dict(name='Blind — LinkedIn Staff front-end onsite structure', date='15 Feb 2022',
                  url='https://www.teamblind.com/post/staff-front-end-engineer-for-ui-onsite-interview-linkedin-rzksfsf4',
                  kind='first-hand', note='Old and front-end, but names the "pragmatic coding" + craftsmanship structure.'),
 'blind-2018': dict(name='Blind — LinkedIn infra/system design thread', date='24 Aug 2018',
                  url='https://www.teamblind.com/post/linkedin-infra-system-design-interview-hb61oh2j',
                  kind='first-hand', note='No questions disclosed; notable only for "2 coding + 3 design" and heavy concurrency emphasis.'),
 'official':  dict(name='LinkedIn recruiter pack — "Staff SI Onsite Prep · CWAI"', date='21 Sep 2026', url=None,
                  kind='official', note='Authoritative. Four modules; Bit.ly and Firefighting Strategy as worked examples.'),
}

BLOCKED = ['LeetCode Discuss (403 on direct fetch — read via search summaries and the reader\'s own links)',
           'Glassdoor (403 — read via search summaries)',
           '1Point3Acres (403)',
           'Blind (partially readable; some threads fetch, some do not)',
           'Reddit (no LinkedIn Staff loop threads surfaced with concrete 2026 questions in these searches)']

# ---------------------------------------------------------------- reported questions
# q, lc(name, number, url), date, idate, level, loc, rnd, diff, follows[], variations, constraints,
# complexity, src[], reports, rec, conf, pattern, covers (workspace item id or None), kind
def Q(**kw):
    kw.setdefault('lc', None); kw.setdefault('variations', ''); kw.setdefault('constraints', '')
    kw.setdefault('complexity', ''); kw.setdefault('follows', []); kw.setdefault('covers', None)
    kw.setdefault('kind', 'reported'); kw.setdefault('idate', '')
    return kw

CODING = [
 Q(q='Letter Combinations of a Phone Number', lc=('Letter Combinations of a Phone Number', 17, 'https://leetcode.com/problems/letter-combinations-of-a-phone-number/'),
   date='Sep 2026', level='Staff', loc='—', rnd='Coding', diff='Medium',
   follows=['Iterative version', 'Lazy/streaming output', 'Dictionary-ranked completions'],
   complexity='O(4ⁿ·n), output-bound', src=['reader', 'lc-tag'], reports=2, rec='recurring', conf='HIGH',
   pattern='Backtracking', covers='prob.letters',
   variations='Appears in LeetCode\'s LinkedIn six-month tagged list, which the reader\'s own list also contains.'),
 Q(q='All O`one Data Structure', lc=('All O`one Data Structure', 432, 'https://leetcode.com/problems/all-oone-data-structure/'),
   date='Sep 2026 (reader) · Jul 2025 (LC report)', level='Staff', loc='—', rnd='Coding / screening', diff='Hard',
   follows=['Guarantee O(1) for every operation', 'Thread-safety', 'Return all max keys'],
   complexity='O(1) average per op', src=['reader', 'lc-staff'], reports=2, rec='recurring', conf='HIGH',
   pattern='Data structure design', covers='prob.allone'),
 Q(q='Word Ladder', lc=('Word Ladder', 127, 'https://leetcode.com/problems/word-ladder/'),
   date='Sep 2026 (reader) · Jul 2025 (LC report)', level='Staff', loc='—', rnd='Coding / screening', diff='Hard',
   follows=['Bidirectional BFS', 'Return all shortest ladders', 'Huge dictionary'],
   complexity='O(N·L²)', src=['reader', 'lc-staff'], reports=2, rec='recurring', conf='HIGH',
   pattern='BFS / Graphs', covers='prob.wordladder'),
 Q(q='The Maze — ball rolls until it hits a wall', lc=('The Maze', 490, 'https://leetcode.com/problems/the-maze/'),
   date='Sep 2026', level='Staff', loc='—', rnd='Coding', diff='Medium',
   follows=['Maze II shortest distance', 'Generate a maze with a guaranteed path', 'Validate the outer wall'],
   complexity='O(R·C·max(R,C))', src=['reader', 'exp-cand'], reports=2, rec='recurring', conf='HIGH',
   pattern='BFS / Simulation', covers='prob.maze',
   variations='A maze **class** to debug and extend was reported in the ≈Mar 2026 AI-coding round — same shape, different framing.'),
 Q(q='Insert Delete GetRandom O(1) — duplicates allowed', lc=('Insert Delete GetRandom O(1) - Duplicates allowed', 381, 'https://leetcode.com/problems/insert-delete-getrandom-o1-duplicates-allowed/'),
   date='Sep 2026 (reader) · Oct 2025 ("design a random set", Taro)', level='Staff / Senior', loc='— / US',
   rnd='Coding', diff='Hard', follows=['Remove all occurrences', 'Weighted random', 'Thread-safety'],
   complexity='Average O(1)', src=['reader', 'taro-infra'], reports=2, rec='recurring', conf='HIGH',
   pattern='Data structure design', covers='prob.rgetrandom'),
 Q(q='Find K Closest Elements', lc=('Find K Closest Elements', 658, 'https://leetcode.com/problems/find-k-closest-elements/'),
   date='Sep 2026', level='Staff', loc='—', rnd='Coding', diff='Medium',
   follows=['Unsorted input', 'Streaming k', 'Sort by distance'], complexity='O(log(n−k) + k)',
   src=['reader', 'lc-tag'], reports=2, rec='recurring', conf='HIGH', pattern='Binary search', covers='prob.kclosest'),
 Q(q='Find the Celebrity', lc=('Find the Celebrity', 277, 'https://leetcode.com/problems/find-the-celebrity/'),
   date='Sep 2026 (reader) · early 2026 (Glassdoor DSA round)', level='Staff / SWE', loc='—', rnd='Coding', diff='Medium',
   follows=['Minimise calls to Knows()', 'Expensive/remote Knows()', 'Prove the elimination argument'],
   complexity='O(n) calls', src=['reader', 'gd-swe'], reports=2, rec='recurring', conf='HIGH',
   pattern='Elimination / API cost', covers='prob.celebrity'),
 Q(q='Max Consecutive Ones III', lc=('Max Consecutive Ones III', 1004, 'https://leetcode.com/problems/max-consecutive-ones-iii/'),
   date='Sep 2026', level='Staff', loc='—', rnd='Coding', diff='Medium',
   follows=['Return the window', 'Stream the input', 'At most k distinct instead of zeros'], complexity='O(n)',
   src=['reader', 'lc-tag'], reports=2, rec='recurring', conf='HIGH', pattern='Sliding window', covers='prob.maxones'),
 Q(q='Shortest Word Distance II (the design variant)', lc=('Shortest Word Distance II', 244, 'https://leetcode.com/problems/shortest-word-distance-ii/'),
   date='Sep 2026', level='Staff', loc='—', rnd='Coding', diff='Medium',
   follows=['word1 == word2 (III)', 'Document updates', 'Cache repeated pairs'], complexity='Build O(n), query O(a+b)',
   src=['reader', 'lc-tag'], reports=2, rec='recurring', conf='HIGH', pattern='Data structure design', covers='prob.swd2'),
 Q(q='Bulb Switcher', lc=('Bulb Switcher', 319, 'https://leetcode.com/problems/bulb-switcher/'),
   date='Sep 2026', level='Staff', loc='—', rnd='Coding', diff='Medium',
   follows=['Prove the perfect-square argument', 'Changed toggle rules'], complexity='O(1)',
   src=['reader'], reports=1, rec='single', conf='HIGH', pattern='Maths / reasoning', covers='prob.bulb',
   variations='Reader-supplied, so first-party — but only one source, so treat the *specific* problem as a single signal.'),
 Q(q='Binary Tree Upside Down (reader notes a variant with a 0/1 right child)',
   lc=('Binary Tree Upside Down', 156, 'https://leetcode.com/problems/binary-tree-upside-down/'),
   date='Sep 2026 (reader, twice)', level='Staff', loc='—', rnd='Coding / phone screen', diff='Medium',
   follows=['Iterative O(1) space', 'Reverse the transform', 'Detect cycles after rewiring'], complexity='O(n)',
   src=['reader', 'lc-compact'], reports=2, rec='recurring', conf='HIGH', pattern='Trees / pointers', covers='prob.upsidedown'),
 Q(q='Find Leaves of Binary Tree', lc=('Find Leaves of Binary Tree', 366, 'https://leetcode.com/problems/find-leaves-of-binary-tree/'),
   date='Sep 2026', level='Staff', loc='—', rnd='Coding', diff='Medium',
   follows=['Return nodes not values', 'Iterative', 'N-ary trees'], complexity='O(n)',
   src=['reader', 'lc-tag'], reports=2, rec='recurring', conf='HIGH', pattern='Trees', covers='prob.findleaves'),
 Q(q='Merge two keyed trees, summing values (n-ary variant of Merge Two Binary Trees)',
   lc=('Merge Two Binary Trees', 617, 'https://leetcode.com/problems/merge-two-binary-trees/'),
   date='Sep 2026', level='Staff', loc='—', rnd='Coding', diff='Medium',
   follows=['Merge k trees', 'Iterative for deep trees', 'Max instead of sum (combiner seam)'],
   constraints='Reader\'s wording: values represent the sum of this and child values; absent branches are created; keys unique '
               'among siblings; children in any order.',
   complexity='O(a + b)', src=['reader'], reports=1, rec='single', conf='HIGH', pattern='Trees / n-ary', covers='prob.mergetrees'),
 Q(q='Minimum degree of connection between two users; follow-up: return the path',
   lc=None, date='Sep 2026', level='Staff', loc='—', rnd='Coding', diff='Medium',
   follows=['Return the path', 'Cap at 3rd degree', 'Graph does not fit on one machine', 'Weighted edges'],
   constraints='Reader\'s note: expected answer is bidirectional BFS.', complexity='~2·b^(d/2)',
   src=['reader'], reports=1, rec='single', conf='HIGH', pattern='Bidirectional BFS', covers='prob.degree',
   variations='The most LinkedIn-specific coding question on the list — the social graph is the product.'),
 Q(q='Valid Parentheses (reader notes the LinkedIn six-month tag; a 2025 report used a variant with integers and special characters)',
   lc=('Valid Parentheses', 20, 'https://leetcode.com/problems/valid-parentheses/'),
   date='Sep 2026 (reader) · 2025 (Glassdoor phone screen)', level='Staff / SWE', loc='—', rnd='Phone screen', diff='Easy',
   follows=['Multi-character tokens', 'Report the mismatch index', 'Arbitrary bracket sets'], complexity='O(n)',
   src=['reader', 'gd-swe'], reports=2, rec='recurring', conf='HIGH', pattern='Stack', covers='bank.1'),
 Q(q='Build a compact tree from a given tree (n-ary, 0–N children)', lc=None,
   date='Sep 2026 (reader link)', idate='phone screen', level='—', loc='—', rnd='Phone screen', diff='Medium',
   follows=['Merge identical sibling labels', 'Iterative for deep chains', 'Idempotence as a property test'],
   constraints='The reporter noted missing one edge case — the root collapsing is the usual one.',
   complexity='O(n)', src=['reader', 'lc-compact'], reports=1, rec='single', conf='MEDIUM',
   pattern='Trees / n-ary', covers='prob.compact'),
 Q(q='Given a sorted array find a valid triangle and return the sides; follow-up: count the triangles', lc=('Valid Triangle Number', 611, 'https://leetcode.com/problems/valid-triangle-number/'),
   date='Sep 2026 (reader link)', level='—', loc='—', rnd='Phone screen', diff='Medium',
   follows=['Count all triples', 'Return all triples', 'Unsorted input'],
   constraints='Reporter\'s note: "constant time complexity needed" — read as O(n) existence / O(n²) counting.',
   complexity='O(n) find, O(n²) count', src=['reader', 'lc-compact'], reports=1, rec='single', conf='MEDIUM',
   pattern='Two pointers', covers='prob.triangle'),
 Q(q='Booths and groups: maximise the experience factor (drones × robots over a range)', lc=None,
   date='Sep 2026', level='Staff', loc='—', rnd='Coding', diff='Hard',
   follows=['10⁶ queries', 'Updatable booths (Fenwick tree)', 'k types instead of two'],
   constraints='Objective is ambiguous as stated — clarify whether ranges are given, chosen within, or chosen freely.',
   complexity='O(m) build, O(1) per given range', src=['reader'], reports=1, rec='single', conf='HIGH',
   pattern='Prefix sums / range queries', covers='prob.booths'),
 Q(q='Implement an LFU-like data structure', lc=('LFU Cache', 460, 'https://leetcode.com/problems/lfu-cache/'),
   date='18 Jul 2025', idate='Jul 2025', level='Staff', loc='Sunnyvale, US', rnd='Phone screen', diff='Hard',
   follows=['GetRank() with LRU tiebreak (AI round variant)', 'Thread-safety', 'TTL'],
   complexity='O(1) get/put', src=['taro-staff', 'hi-ai', 'lc-staff'], reports=3, rec='recurring', conf='HIGH',
   pattern='Data structure design', covers='ai.drill.lfurank',
   variations='Appears as a plain LFU in a 2025 phone screen and as LFU + GetRank() in 2026 AI-round reports.'),
 Q(q='Repeated DNA Sequences — all 10-letter sequences occurring more than once, ascending', lc=('Repeated DNA Sequences', 187, 'https://leetcode.com/problems/repeated-dna-sequences/'),
   date='30 Sep 2025', idate='Sep 2025', level='Senior SWE, Infrastructure', loc='Virtual', rnd='Coding 1', diff='Medium',
   follows=['Rolling hash / 2-bit encoding', '3-billion-character genome', 'Return positions'],
   constraints='Reporter noted frequent interviewer interruptions.', complexity='O(n)',
   src=['blind-infra'], reports=1, rec='single', conf='MEDIUM', pattern='Hashing / sliding window', covers='prob.dna'),
 Q(q='Implement getBuildOrder() given getDependencies() (package build order)', lc=('Course Schedule II', 210, 'https://leetcode.com/problems/course-schedule-ii/'),
   date='30 Sep 2025', idate='Sep 2025', level='Senior SWE, Infrastructure', loc='Virtual', rnd='Coding 2', diff='Medium',
   follows=['Report cycle members', 'Parallel build waves', 'Incremental rebuild'], complexity='O(V+E)',
   src=['blind-infra', 'gd-swe'], reports=2, rec='recurring', conf='HIGH', pattern='Topological sort', covers='prob.buildorder'),
 Q(q='Tree traversal over a nested object structure', lc=('Nested List Weight Sum II', 364, 'https://leetcode.com/problems/nested-list-weight-sum-ii/'),
   date='≈ Mar 2026', idate='≈ Feb 2026', level='Senior SWE / L5', loc='United States', rnd='Phone screen', diff='Medium',
   follows=['Iterative', 'Very deep nesting'], complexity='O(n)',
   src=['exp-cand', 'lc-tag'], reports=2, rec='recurring', conf='HIGH', pattern='Trees / nested DFS', covers='prob.nested2'),
 Q(q='Given a string where you can make certain edits, determine whether it can become a palindrome',
   lc=('Valid Palindrome II', 680, 'https://leetcode.com/problems/valid-palindrome-ii/'),
   date='≈ Mar 2026', level='Senior SWE / L5', loc='United States', rnd='Bonus coding', diff='Medium',
   follows=['k edits instead of one', 'Return the deleted positions'], complexity='O(n) / O(n²) for k',
   src=['exp-cand'], reports=1, rec='single', conf='MEDIUM', pattern='Two pointers', covers='prob.palindrome'),
 Q(q='Medium string-manipulation question with a **concurrency follow-up**', lc=None,
   date='Mar 2026', idate='Mar 2026', level='SWE', loc='—', rnd='Phone screen', diff='Medium',
   follows=['Make it thread-safe', 'Concurrency reasoning on the phone screen'], complexity='—',
   src=['gd-swe'], reports=1, rec='single', conf='MEDIUM', pattern='Concurrency', covers='pat.conc',
   variations='Notable because the concurrency pivot appeared as early as the phone screen, not only onsite.'),
 Q(q='OS and networking fundamentals: TCP vs UDP, paging, stack vs heap — alongside one coding question',
   lc=None, date='1 Oct 2025', idate='Oct 2025', level='Senior SWE, Infrastructure', loc='United States',
   rnd='Technical screen', diff='—', follows=['Design a random set, with a follow-up'], complexity='—',
   src=['taro-infra'], reports=1, rec='single', conf='MEDIUM', pattern='Systems fundamentals', covers=None,
   variations='The only report of pure CS-fundamentals questioning. Relevant because the reader\'s role is Systems & Infrastructure.'),
 Q(q='DSA rounds covering linked lists, BFS and the celebrity problem', lc=None,
   date='early 2026', level='SWE', loc='—', rnd='Coding', diff='Medium',
   follows=[], complexity='—', src=['gd-swe'], reports=1, rec='single', conf='LOW',
   pattern='Mixed', covers=None, variations='Aggregated Glassdoor summary; thin on specifics.'),
]

AI = [
 Q(q='LRU cache, built with the AI assistant available', lc=('LRU Cache', 146, 'https://leetcode.com/problems/lru-cache/'),
   date='20 Feb 2026', level='SWE (all levels)', loc='—', rnd='AI coding', diff='Medium',
   follows=['Concurrency and multithreading', 'Race conditions and synchronisation', 'How would you productionise it?'],
   constraints='CoderPad AI Assist; the assistant cannot edit your file — you copy code across yourself.',
   complexity='O(1)', src=['hi-ai', 'cond', 'official'], reports=2, rec='recurring', conf='HIGH',
   pattern='Cache design + production pivot', covers='prob.lru'),
 Q(q='LFU cache with a GetRank() function, LRU as the tiebreaker', lc=('LFU Cache', 460, 'https://leetcode.com/problems/lfu-cache/'),
   date='20 Feb 2026', level='SWE', loc='—', rnd='AI coding', diff='Hard',
   follows=['Complexity of GetRank()', 'Keep get/put O(1)', 'Thread-safety'],
   complexity='O(1) get/put; rank is not O(1) with bucket lists', src=['hi-ai'], reports=1, rec='single', conf='MEDIUM',
   pattern='Cache design', covers='ai.drill.lfurank'),
 Q(q='Merge-intervals variant where you choose the data structure', lc=('Merge Intervals', 56, 'https://leetcode.com/problems/merge-intervals/'),
   date='Feb–Jun 2026', level='SWE', loc='—', rnd='AI coding', diff='Medium',
   follows=['Streaming intervals', 'Overlap queries', 'Millions of intervals'], complexity='O(log n + k) per op as a class',
   src=['hi-ai', 'cond'], reports=2, rec='recurring', conf='HIGH', pattern='Intervals as a class', covers='prob.intervals'),
 Q(q='Structured/JSON-like data processing: build the classes and transform the records',
   lc=None, date='Feb–Jun 2026', level='SWE', loc='—', rnd='AI coding', diff='Medium',
   follows=['Malformed or missing fields', 'Edge cases', 'Performance at scale'], complexity='O(n)',
   src=['hi-ai', 'cond'], reports=2, rec='recurring', conf='HIGH', pattern='Parsing + modelling', covers='ai.drill.records'),
 Q(q='Debug and complete a maze implementation class (HackerRank with a built-in AI assistant)', lc=('The Maze', 490, 'https://leetcode.com/problems/the-maze/'),
   date='≈ Mar 2026', idate='≈ Feb 2026', level='Senior SWE / L5', loc='United States', rnd='AI coding', diff='Medium',
   follows=['"How would you make sure the maze is well formed, including the outer wall?"',
            '"Given a start and end position, how would you generate the maze so there is always a path?"',
            '"Why did you choose this AI-generated approach over the other options?"',
            '"How would you test each change?"',
            '"If this went to production, what would you change?"'],
   constraints='HackerRank with built-in AI assistant — a different platform from the CoderPad reports and from the official pack.',
   complexity='—', src=['exp-cand'], reports=1, rec='single', conf='HIGH',
   pattern='Debug → extend → harden', covers='ai.ex.debug',
   variations='The only report with the full verbatim follow-up chain. Rehearse these five questions in order.'),
 Q(q='Three-phase arc: debug existing code → implement a feature → optimise for edge cases or larger inputs',
   lc=None, date='2026', level='SWE', loc='—', rnd='AI coding', diff='—',
   follows=['Timed by phase', 'Ends on production concerns'], complexity='—',
   src=['hi-fmt', 'exp-cand'], reports=2, rec='recurring', conf='HIGH', pattern='Round format', covers='ai.sc.sc1',
   kind='reported'),
]

DESIGN = [
 Q(q='Design a rate limiter', lc=None, date='≈ Aug 2026 ("asked a month ago")', level='SWE', loc='—',
   rnd='System design', diff='—',
   follows=['Distributed counters', 'Per-member vs per-key limits', 'Behaviour when the shared store is down', 'Fairness and bursts'],
   complexity='—', src=['exp-bank'], reports=1, rec='single', conf='MEDIUM', pattern='Infrastructure primitive',
   covers='des.ratelimit', variations='The most recent design prompt found in either research pass.'),
 Q(q='Design a job scheduler', lc=None, date='30 Sep 2025', idate='Sep 2025', level='Senior SWE, Infrastructure',
   loc='Virtual', rnd='System design', diff='—',
   follows=['Exactly-once vs at-least-once', 'Missed and overdue jobs', 'Leader election / partitioning', 'Back-pressure'],
   constraints='Interviewer closed with "since all the trade-offs are covered, I don\'t have any more questions".',
   complexity='—', src=['blind-infra'], reports=1, rec='single', conf='HIGH', pattern='Distributed scheduling',
   covers='des.scheduler'),
 Q(q='Design a distributed inverted index / search system (Elasticsearch-like)', lc=None, date='12 May 2025',
   idate='May 2025', level='Staff Engineer', loc='India', rnd='System design', diff='—',
   follows=['Sharding and replication of the index', 'Near-real-time indexing', 'Query fan-out and merge', 'Ranking'],
   complexity='—', src=['taro-india'], reports=1, rec='single', conf='HIGH', pattern='Search / storage',
   covers='des.index', variations='Closest data point to the reader\'s own loop: Staff, India, infrastructure.'),
 Q(q='Design the backend for autosuggest / typeahead', lc=None, date='≈ Mar 2026 · plus "typeahead for person search" ≈2025',
   level='Senior SWE / L5', loc='United States', rnd='System design', diff='—',
   follows=['Ranking and personalisation', 'Index build and refresh', 'Latency budget', 'Typos'],
   complexity='—', src=['exp-cand', 'exp-bank', 'gd-swe'], reports=3, rec='recurring', conf='HIGH',
   pattern='Retrieval + ranking', covers='des.autosuggest'),
 Q(q='Design a Kafka-like distributed message queue', lc=None, date='Jun 2025', level='Staff SWE', loc='—',
   rnd='System design', diff='—',
   follows=['Partitioning and ordering', 'Replication and ISR', 'Consumer groups', 'Exactly-once semantics'],
   complexity='—', src=['lc-staff'], reports=1, rec='single', conf='MEDIUM', pattern='Messaging', covers='des.queue'),
 Q(q='Design a LinkedIn-like system that intercepts malicious requests and denies them', lc=None, date='undated',
   level='SWE', loc='—', rnd='System design', diff='—',
   follows=['Signal collection', 'Real-time vs batch scoring', 'False positives', 'Rule updates without redeploy'],
   complexity='—', src=['gd-swe'], reports=1, rec='single', conf='LOW', pattern='Trust & safety', covers='des.abuse',
   variations='Single, undated report. Practise it; do not weight it.'),
 Q(q='Design a metrics gathering system (collection, time-series storage, monitoring and alerting on top)',
   lc=None, date='2025–2026 (aggregated)', level='SWE', loc='—', rnd='System design', diff='—',
   follows=['Ingestion rate and cardinality', 'Downsampling and retention', 'Alert evaluation at scale'],
   complexity='—', src=['gd-swe'], reports=1, rec='single', conf='LOW', pattern='Observability platform', covers=None,
   variations='Not covered in the workspace — flagged as a gap.'),
 Q(q='Design a flexible in-memory cache with customisable capacity and eviction policies', lc=None,
   date='2025 (Taro Staff summary)', level='Staff', loc='—', rnd='System design / design-y coding', diff='—',
   follows=['TTL', 'Ranked eviction', 'Concurrency'], complexity='—',
   src=['taro-staff', 'exp-bank'], reports=2, rec='recurring', conf='MEDIUM', pattern='Cache design', covers='prob.lru'),
 Q(q='Design a calendar (low-level design)', lc=None, date='≈ Aug/Sep 2026 ("asked 22 days ago")', level='SWE', loc='—',
   rnd='Design / LLD', diff='—', follows=['Recurring events', 'Time zones and DST', 'Conflict detection'],
   complexity='—', src=['exp-bank'], reports=1, rec='single', conf='MEDIUM', pattern='LLD', covers=None,
   variations='Recent, and not covered in the workspace — flagged as a gap.'),
 Q(q='Design LinkedIn\'s news feed', lc=None, date='2025–2026 (aggregated; also a 2022 first-hand report)',
   level='Staff / SWE', loc='—', rnd='System design', diff='—',
   follows=['Fan-out on write vs read', 'Ranking', 'Freshness vs cost'], complexity='—',
   src=['gd-staff', 'exp-bank'], reports=2, rec='recurring', conf='MEDIUM', pattern='Product platform',
   covers=None, variations='Covered in the main guide (design-twitter), linked from the workspace catalogue.'),
]

# Things guides assert but no candidate reported — kept separate on purpose.
GENERAL = [
 ('People You May Know / job recommendations / notifications', 'Named by several preparation guides as LinkedIn-typical design '
  'topics. No first-hand report surfaced in either pass.', ['exp-bank', 'gd-staff']),
 ('"Design LinkedIn" end to end', 'A staple of paid courses and blogs, not of candidate reports.', ['gd-staff']),
 ('Dedicated concurrency/systems coding round', 'Asserted by two aggregator guides; the closest first-hand evidence is the Mar 2026 '
  'concurrency follow-up on a phone screen and the 2018 Blind thread emphasising multithreading.', ['gd-swe', 'blind-2018']),
]

INFERENCE = [
 ('The AI round will pivot to concurrency and production', 'Every AI-round report ends there, and the official pack lists '
  'production thinking as a scored signal — but the specific pivot for *your* problem is an inference.'),
 ('Graph/tree problems are over-represented because the product is a graph', 'Consistent with the reader\'s list and the tagged '
  'set, but it is a pattern reading, not a reported fact.'),
 ('Systems & Infrastructure loops lean harder on storage, streaming and coordination than product loops', 'Supported by the '
  'official role description and the India Staff report; not directly reported as a question distribution.'),
]
