# -*- coding: utf-8 -*-
"""Web research pass 1 — LinkedIn Staff/Senior loop, collected 21 Sep 2026.

Every entry carries its source and a confidence grade:
  A = reported first-hand with specifics, recent (2025-2026)
  B = reported by an aggregator/guide that summarises candidate reports, or first-hand but thin
  C = single source, undated or older, or a category inferred from guides — never treat as confirmed
"""

DATE = '21 September 2026'

SOURCES = {
 'hi-ai':   dict(name='Hello Interview — "LinkedIn\'s AI-Enabled Coding Interview: How to Prepare"', date='20 Feb 2026',
                 url='https://www.hellointerview.com/blog/linkedin-ai-enabled-coding', kind='guide built on candidate reports', role='SWE all levels', loc='—'),
 'hi-fmt':  dict(name='Hello Interview — AI-enabled coding interview formats', date='2026',
                 url='https://www.hellointerview.com/learn/ai-coding/overview/interview-formats', kind='guide', role='—', loc='—'),
 'cond':    dict(name='Coditioning — LinkedIn SWE AI-enabled coding guide', date='updated 25 Jun 2026',
                 url='https://www.coditioning.com/blog/1406/linkedin-swe-ai-enabled-coding', kind='guide', role='SWE', loc='—'),
 'exp-exp': dict(name='Exponent — LinkedIn Senior SWE (Apps) interview experience (anonymous)', date='≈ Mar 2026',
                 url='https://www.tryexponent.com/experiences/linkedin-senior-software-engineer-interview-dc48e8', kind='first-hand, anonymous', role='Senior SWE / L5', loc='United States'),
 'exp-q':   dict(name='Exponent — LinkedIn system design question bank (recency labels)', date='read 21 Sep 2026',
                 url='https://www.tryexponent.com/questions?company=linkedin&type=system-design', kind='aggregated candidate submissions', role='SWE', loc='—'),
 'taro-in': dict(name='Taro — LinkedIn Staff Engineer interview experience, India (offer)', date='12 May 2025',
                 url='https://www.jointaro.com/interviews/companies/linkedin/experiences/staff-engineer-india-may-12-2025-accepted-offer-neutral-ca8f7d74/', kind='first-hand, anonymous', role='Staff Engineer', loc='India'),
 'blind-in':dict(name='Blind — LinkedIn Senior SWE Infrastructure interview experience (rejected)', date='30 Sep 2025',
                 url='https://www.teamblind.com/post/linkedin-senior-software-engineer-infrastructure-interview-experience-rfq58zbt', kind='first-hand, anonymous', role='Senior SWE, Infrastructure', loc='Virtual'),
 'lc-staff':dict(name='LeetCode Discuss — LinkedIn Staff SWE interview experience (offer)', date='Jun 2025',
                 url='https://leetcode.com/discuss/post/6858262/linkedin-staff-software-engineer-intervi-mg5c/', kind='first-hand, anonymous (read via search summary — page blocks fetching)', role='Staff SWE', loc='—'),
 'blind-sd':dict(name='Blind — "LinkedIn onsite interview System design review"', date='undated',
                 url='https://www.teamblind.com/post/linkedin-onsite-interview-system-design-review-1buxmbjm', kind='first-hand, anonymous (read via search summary)', role='SWE', loc='—'),
 'blind-lv':dict(name='Blind — LinkedIn Staff level / down-levelling discussions', date='2024–2026',
                 url='https://www.teamblind.com/company/LinkedIn/posts/linkedin%20staff', kind='discussion threads', role='Staff', loc='—'),
 'gd':      dict(name='Glassdoor — LinkedIn Staff Software Engineer interview questions', date='2025–2026',
                 url='https://www.glassdoor.com/Interview/LinkedIn-Staff-Software-Engineer-Interview-Questions-EI_IE34865.0,8_KO9,32.htm', kind='aggregated candidate reports', role='Staff SWE', loc='mixed'),
 'dsap':    dict(name='DSA Prep — LinkedIn coding interview questions (2026 guide)', date='2026',
                 url='https://www.dsaprep.dev/blog/linkedin-coding-interview-questions', kind='aggregator', role='IC2–Staff', loc='—'),
 'prepf':   dict(name='Prepfully — LinkedIn SWE interview guide', date='2026',
                 url='https://prepfully.com/interview-guides/linkedin-software-engineer-interview', kind='guide', role='SWE senior/staff', loc='—'),
 'dg':      dict(name='DesignGurus — what to expect in the LinkedIn system design interview', date='2026',
                 url='https://www.designgurus.io/answers/detail/what-to-expect-in-the-linkedin-system-design-interview', kind='guide', role='SWE', loc='—'),
 'lcwise':  dict(name='LeetCode company-tagged question sets (LinkedIn)', date='Jul 2026 snapshot',
                 url='https://github.com/snehasishroy/leetcode-companywise-interview-questions', kind='aggregated tag data', role='—', loc='—'),
}

# round, question, date, role, loc, source keys, recurrence, confidence, follow-ups, pattern, practice
Q = [
 # ---------------- CODING ----------------
 dict(r='coding', q='Max Stack — stack with push/pop/top/peekMax/popMax', d='2024–2026', role='Senior/Staff', loc='—',
      src=['lcwise', 'dsap'], rec='high', conf='B',
      fu=['Make popMax O(log n)', 'What breaks with duplicates?', 'Thread-safety'],
      pat='Design + heap/ordered structure + lazy deletion',
      prep='Implement twice: two-stack O(n) popMax, then TreeMap/SortedSet + doubly linked list for O(log n).'),
 dict(r='coding', q='Nested List Weight Sum I / II', d='2024–2026', role='Senior/Staff', loc='—',
      src=['lcwise', 'dsap'], rec='high', conf='B',
      fu=['Invert the weighting (II)', 'Iterative vs recursive', 'Huge nesting depth'],
      pat='DFS/BFS on nested structure',
      prep='Solve II with level sums, no depth pre-pass. This is LinkedIn-classic.'),
 dict(r='coding', q='Find Leaves of Binary Tree', d='2024–2026', role='Senior/Staff', loc='—',
      src=['lcwise', 'dsap'], rec='high', conf='B',
      fu=['Return by height', 'Iterative version'], pat='Post-order height bucketing',
      prep='Height-from-bottom indexing into a list of lists.'),
 dict(r='coding', q='Lowest Common Ancestor of a Binary Tree', d='2024–2026', role='Senior/Staff', loc='—',
      src=['lcwise', 'dsap'], rec='high', conf='B',
      fu=['No parent pointers vs with parent pointers', 'k nodes instead of 2', 'BST variant'],
      pat='Recursion returning found-nodes', prep='Do plain LCA, LCA with parent pointers, and LCA of k nodes.'),
 dict(r='coding', q='Minimum Window Substring', d='2024–2025', role='Senior/Staff', loc='—',
      src=['lcwise', 'dsap'], rec='high', conf='B', fu=['Stream the input', 'Unicode / large alphabet'],
      pat='Sliding window with counts', prep='Write it cleanly in one pass with a need/have counter.'),
 dict(r='coding', q='Search in Rotated Sorted Array II (with duplicates)', d='2025', role='SWE phone screen', loc='—',
      src=['dsap', 'gd'], rec='medium', conf='B', fu=['Why does O(log n) break with duplicates?', 'Find rotation point'],
      pat='Binary search on rotated array', prep='Be ready to state the O(n) worst case and why.'),
 dict(r='coding', q='Valid Parentheses variant (string contains integers and special characters)', d='2025', role='SWE phone screen', loc='—',
      src=['dsap'], rec='medium', conf='B', fu=['Support arbitrary bracket sets', 'Report the index of the first mismatch'],
      pat='Stack', prep='Practise the variant where tokens are multi-character.'),
 dict(r='coding', q='All O`one Data Structure', d='Jul 2025', role='Staff (screening)', loc='—',
      src=['lc-staff'], rec='medium', conf='B', fu=['Guarantee O(1) for every op', 'Thread-safety'],
      pat='Doubly linked list of count buckets + hash map',
      prep='This is the same muscle as LFU: bucket list + map. Build it from scratch.'),
 dict(r='coding', q='Word Ladder', d='Jul 2025', role='Staff (screening)', loc='—',
      src=['lc-staff'], rec='medium', conf='B', fu=['Bidirectional BFS', 'Return all shortest paths (Ladder II)'],
      pat='BFS on implicit graph', prep='Bidirectional BFS + the wildcard-bucket adjacency trick.'),
 dict(r='coding', q='Repeated DNA Sequences — all 10-letter sequences occurring more than once, ascending order', d='30 Sep 2025',
      role='Senior SWE, Infrastructure', loc='Virtual', src=['blind-in'], rec='one-off', conf='A',
      fu=['Rolling hash instead of substrings', 'Memory for a 3-billion-character genome', 'Interviewer interrupted frequently — keep narrating'],
      pat='Sliding window + hashing (Rabin-Karp)', prep='Do the HashSet version, then the 2-bit-encoded rolling hash version, then say when each is right.'),
 dict(r='coding', q='Topological sort — implement getBuildOrder() given getDependencies()', d='30 Sep 2025',
      role='Senior SWE, Infrastructure', loc='Virtual', src=['blind-in'], rec='medium', conf='A',
      fu=['Detect and report cycles', 'Parallel build waves', 'Incremental rebuild when one node changes'],
      pat='Kahn / DFS topological sort',
      prep='Kahn with in-degrees; return the cycle when one exists; then group into parallel waves — that is your AIC tier ordering in disguise.'),
 dict(r='coding', q='Tree traversal over a nested object structure (phone screen)', d='≈ Mar 2026', role='Senior SWE / L5', loc='US',
      src=['exp-exp'], rec='medium', conf='A', fu=['Iterative version', 'Very deep nesting'],
      pat='DFS over heterogeneous nested data', prep='Same family as Nested List Weight Sum — practise both.'),
 dict(r='coding', q='Given a string where you can make certain edits, determine whether it can become a palindrome', d='≈ Mar 2026',
      role='Senior SWE / L5', loc='US', src=['exp-exp'], rec='one-off', conf='A',
      fu=['Allow k edits instead of one', 'Return the edit positions'],
      pat='Two pointers with a mismatch budget', prep='Valid Palindrome II, then generalise to k deletions with DP.'),
 dict(r='coding', q='LRU Cache (implement from scratch)', d='2025–2026', role='all levels', loc='—',
      src=['hi-ai', 'cond', 'prepf'], rec='high', conf='A',
      fu=['Make it thread-safe', 'Where are the race conditions?', 'Productionise it: metrics, eviction policy, sizing'],
      pat='Hash map + doubly linked list',
      prep='Write it without a template in under 12 minutes, then add locking and explain the contention trade-off.'),
 dict(r='coding', q='Flexible in-memory cache with customisable capacity and pluggable eviction policy', d='undated',
      role='SWE onsite', loc='—', src=['blind-sd', 'exp-q'], rec='medium', conf='C',
      fu=['Add TTL', 'Add a ranked/priority eviction', 'Make it concurrent'],
      pat='Design-y coding: interfaces + strategy pattern + O(1) structures',
      prep='Design an ICacheEvictionPolicy seam so LRU/LFU/TTL plug in. LinkedIn likes design-flavoured coding.'),
 dict(r='coding', q='Concurrency-flavoured coding round (LinkedIn-specific in several guides)', d='2025–2026', role='Senior/Staff', loc='—',
      src=['dsap', 'hi-ai'], rec='medium', conf='B',
      fu=['Add synchronisation to a single-threaded solution', 'Identify race conditions', 'Reader-heavy vs writer-heavy trade-offs'],
      pat='Locks, concurrent collections, immutability',
      prep='Know ConcurrentDictionary, ReaderWriterLockSlim, Interlocked, and when a lock-free read path is worth it — in C#.'),
 # ---------------- AI CODING ----------------
 dict(r='ai', q='LRU Cache, built with an AI assistant in the panel', d='Feb 2026', role='SWE', loc='—',
      src=['hi-ai'], rec='high', conf='A',
      fu=['Concurrency and multithreading', 'Synchronisation and race conditions', 'How would you productionise it?'],
      pat='Known data structure + AI-assisted implementation + production follow-ups',
      prep='Practise prompting for the skeleton, then reviewing and correcting it out loud.'),
 dict(r='ai', q='LFU Cache with a GetRank() function, LRU used as the tie-breaker', d='Feb 2026', role='SWE', loc='—',
      src=['hi-ai'], rec='medium', conf='A',
      fu=['Complexity of GetRank()', 'Keep O(1) get/put while supporting rank', 'Thread-safety'],
      pat='Frequency buckets + ordering within a bucket',
      prep='This is the hardest reported variant — build LFU first, then add ranking.'),
 dict(r='ai', q='Merge-intervals variant where you must pick the data structure yourself', d='Feb 2026', role='SWE', loc='—',
      src=['hi-ai', 'cond'], rec='medium', conf='A',
      fu=['Streaming intervals', 'Overlap queries', 'Scale to millions of intervals'],
      pat='Interval manager: sorted structure + merge on insert',
      prep='Build an IntervalSet class with Add/Remove/Query rather than a one-shot function.'),
 dict(r='ai', q='Structured data processing: build classes from scratch for JSON-like objects and transform them', d='Feb–Jun 2026',
      role='SWE', loc='—', src=['hi-ai', 'cond'], rec='medium', conf='A',
      fu=['Malformed or missing fields', 'Edge cases', 'Performance at scale'],
      pat='Parsing + modelling + defensive handling',
      prep='Write the model classes and a tolerant parser; make the AI generate test fixtures, not your design.'),
 dict(r='ai', q='Debug and complete a maze implementation class (HackerRank with built-in AI assistant)', d='≈ Mar 2026',
      role='Senior SWE / L5', loc='US', src=['exp-exp'], rec='one-off', conf='A',
      fu=['How would you make sure the maze is well formed, including the outer wall?',
          'Given a start and end position, how would you generate the maze so there is always a path?',
          'Why did you choose this AI-generated approach over the other options?',
          'How would you test each change?',
          'If this went to production, what would you change?'],
      pat='Debug-then-extend an existing class; grid/graph reasoning; justify the approach you accepted',
      prep='Practise reading unfamiliar code fast, fixing it, then extending it — and always answering "why this approach".'),
 dict(r='ai', q='Three-phase arc reported across AI-enabled rounds: debug existing code → implement a new feature → optimise for edge cases or larger inputs',
      d='2026', role='SWE', loc='—', src=['hi-fmt'], rec='high', conf='B',
      fu=['Each phase is timed by the interviewer', 'Expect a pivot to production concerns at the end'],
      pat='Structured AI round format',
      prep='Rehearse the arc, not just the problems: 10 min debug, 15 min feature, 10 min hardening.'),
 # ---------------- SYSTEM DESIGN ----------------
 dict(r='design', q='Design a rate limiter', d='≈ Aug 2026 ("asked a month ago")', role='SWE', loc='—',
      src=['exp-q'], rec='high', conf='B',
      fu=['Distributed counters', 'Per-member vs per-API-key limits', 'What happens when Redis is down?', 'Fairness and burst handling'],
      pat='Token bucket / sliding window + shared state',
      prep='Know token bucket, sliding-window log and counter, plus the distributed-state trade-off cold. Highest-recency design signal found.'),
 dict(r='design', q='Design a job scheduler', d='30 Sep 2025', role='Senior SWE, Infrastructure', loc='Virtual',
      src=['blind-in'], rec='medium', conf='A',
      fu=['Exactly-once vs at-least-once execution', 'Missed and overdue jobs', 'Leader election / partitioning of the schedule', 'Back-pressure'],
      pat='Distributed scheduling + durable queue + idempotency',
      prep='The reporter said the interviewer ended with "since all the trade-offs are covered, I don\'t have any more questions" — lead with trade-offs.'),
 dict(r='design', q='Design a distributed inverted index / search system (Elasticsearch-like)', d='12 May 2025',
      role='Staff Engineer', loc='India', src=['taro-in'], rec='medium', conf='A',
      fu=['Sharding and replication of the index', 'Near-real-time indexing', 'Query fan-out and merging', 'Ranking'],
      pat='Index build + serving split, fan-out/fan-in',
      prep='Most relevant India + Staff data point found. Practise indexing pipeline and query path separately.'),
 dict(r='design', q='Design a LinkedIn-like system that intercepts malicious requests and denies them', d='undated',
      role='SWE onsite', loc='—', src=['blind-sd'], rec='one-off', conf='C',
      fu=['Signal collection', 'Real-time vs batch scoring', 'False positives', 'Rule updates without redeploy'],
      pat='Edge filtering + streaming features + policy engine',
      prep='Treat as abuse/trust-and-safety design: edge → feature store → scoring → policy → feedback loop.'),
 dict(r='design', q='Design a Kafka-like distributed message queue', d='Jun 2025', role='Staff SWE', loc='—',
      src=['lc-staff'], rec='medium', conf='B',
      fu=['Partitioning and ordering', 'Replication and ISR', 'Consumer groups and rebalancing', 'Exactly-once semantics'],
      pat='Log-structured storage + partitioned consumption',
      prep='LinkedIn invented Kafka — expect depth, not name-dropping. Know the log, the ISR, and offset management.'),
 dict(r='design', q='Design the backend for an autosuggest / autocomplete feature', d='≈ Mar 2026', role='Senior SWE / L5', loc='US',
      src=['exp-exp', 'exp-q'], rec='high', conf='A',
      fu=['Ranking and personalisation', 'Index build and refresh', 'Latency budget', 'Typos and prefix explosion'],
      pat='Trie / FST + ranking + caching',
      prep='Also reported as "typeahead autocomplete for person search in LinkedIn". Have the LinkedIn-flavoured version ready.'),
 dict(r='design', q='Design a calendar (low-level design)', d='≈ Aug/Sep 2026 ("asked 22 days ago")', role='SWE', loc='—',
      src=['exp-q'], rec='medium', conf='B',
      fu=['Recurring events', 'Time zones and DST', 'Conflict detection', 'Interfaces and extensibility'],
      pat='LLD: entities, interfaces, invariants',
      prep='Recent. Practise an LLD with clean interfaces — it overlaps the craftsmanship round.'),
 dict(r='design', q='Design and implement a ranked cache system', d='≈ 2024', role='SWE', loc='—',
      src=['exp-q'], rec='medium', conf='C',
      fu=['Ranking function', 'Eviction under rank', 'Concurrency'],
      pat='Cache + ordering structure',
      prep='Pairs with the AI-round LFU+GetRank report — the same idea appears in both loops.'),
 dict(r='design', q='Product-centric LinkedIn systems: feed, People You May Know, job recommendations, notifications, messaging',
      d='2025–2026', role='Senior/Staff', loc='—', src=['dg', 'prepf', 'gd'], rec='high', conf='B',
      fu=['Candidate generation vs ranking', 'Precompute vs online', 'Fan-out on write vs read', 'Freshness vs cost'],
      pat='Two-stage retrieval + ranking, graph traversal at scale',
      prep='LinkedIn design rounds are product-centric. Be able to design any one of these with a retrieval/ranking split.'),
 # ---------------- HIRING MANAGER ----------------
 dict(r='hm', q='Walk me through your career progression', d='≈ Mar 2026', role='Senior SWE / L5', loc='US',
      src=['exp-exp'], rec='high', conf='A',
      fu=['What triggered each promotion?', 'Why did you move when you did?', 'What scope changed each time?'],
      pat='Narrative of growing scope',
      prep='Three-minute arc ending at platform-wide scope, with the trigger for each step.'),
 dict(r='hm', q='We have a platform product used by 5,000 teams. How would you get those teams to migrate? What about the holdouts?',
      d='≈ Mar 2026', role='Senior SWE / L5', loc='US', src=['exp-exp'], rec='high', conf='A',
      fu=['What if a team refuses?', 'How do you sequence it?', 'How do you measure adoption?'],
      pat='Influence without authority at platform scale',
      prep='This is your Isolated Cloud migration answer almost word for word — 178 teams, tiers, adoption cheaper than resistance.'),
 dict(r='hm', q='Tell me about the most complex project you recently led — including its security aspects and the challenges',
      d='2025', role='Staff SWE', loc='—', src=['lc-staff', 'gd'], rec='high', conf='B',
      fu=['What was your role versus the team\'s?', 'What would you do differently?', 'How did you handle the security review?'],
      pat='Project deep dive with ownership probing',
      prep='AIC: isolation guarantees, egress policy, customer-managed keys, the two incidents.'),
 dict(r='hm', q='Tell me about a conflict or disagreement in a critical project', d='Jun–Jul 2025', role='Staff SWE (screening)', loc='—',
      src=['lc-staff'], rec='high', conf='B',
      fu=['How did it end?', 'What did you concede?', 'What would you do differently?'],
      pat='Conflict + resolution + what changed in the design',
      prep='Jira lead pager objection; SRE lead fallback debate; the overruled phase-one date.'),
 dict(r='hm', q='How do you define a quality product or system?', d='2025', role='Staff SWE', loc='—',
      src=['gd'], rec='medium', conf='B',
      fu=['How do you enforce it across teams you do not own?', 'What do you measure?'],
      pat='Craftsmanship philosophy, made concrete',
      prep='Answer with mechanisms you actually built: readiness checks, computed status, override reviews, health gates.'),
 dict(r='hm', q='What is your strategy for code reviews, especially as a team grows with more junior engineers?', d='2025',
      role='Staff SWE', loc='—', src=['gd'], rec='medium', conf='B',
      fu=['How do you keep review latency low?', 'How do you teach through review?'],
      pat='Mentoring + engineering standards at scale', prep='Have a concrete review philosophy and one mentoring example ready.'),
 dict(r='hm', q='You join a large team that owns a legacy application with poor testing, no monitoring, slow responses and buggy deploys. What do you do?',
      d='2025', role='Staff SWE', loc='—', src=['gd'], rec='medium', conf='B',
      fu=['What do you fix first?', 'How do you get the team to care?', 'How do you show progress to leadership?'],
      pat='Hypothetical turnaround — sequencing and evidence',
      prep='Answer with: measure first, stop the bleeding, make one failure class impossible, then automate.'),
 dict(r='hm', q='Real scenario in the host-manager round: how would you secure Zookeeper access with mTLS, and how long would it take?',
      d='30 Sep 2025', role='Senior SWE, Infrastructure', loc='Virtual', src=['blind-in'], rec='one-off', conf='A',
      fu=['Rollout across the fleet', 'Backwards compatibility during migration', 'Your estimate vs reality'],
      pat='Infra scenario inside a behavioural round — estimation realism is being tested',
      prep='The reporter proposed two quarters; the commenter noted LinkedIn took years. Estimate in phases with named risks.'),
 dict(r='hm', q='Why LinkedIn? Why this role, and why now?', d='2025–2026', role='all', loc='—',
      src=['prepf', 'gd', 'blind-in'], rec='high', conf='B',
      fu=['What would you want to work on here?', 'What do you expect to be different from Atlassian?'],
      pat='Motivation and fit', prep='Must be specific to LinkedIn infrastructure, in your own words.'),
 dict(r='hm', q='Craftsmanship round: code quality, structure, testing, CI/CD, project metrics, reactive systems', d='12 May 2025',
      role='Staff Engineer', loc='India', src=['taro-in'], rec='high', conf='A',
      fu=['How do you test what you built?', 'What metrics did you watch?', 'How did you roll it out safely?'],
      pat='Separate round for engineering excellence',
      prep='India Staff loop had 3 coding + craftsmanship + 2 design + host manager. Prepare craftsmanship as its own round.'),
]

THEMES = {
 'coding': dict(
   summary='Two to three coding rounds at Staff, medium-to-hard, with LinkedIn\'s classic tagged set still showing up: trees, graphs, sliding window, and design-flavoured data structures (Max Stack, All O`one, LRU/LFU). Recent first-hand reports add topological sort and hashing/rolling-hash problems.',
   themes=['Design-flavoured data structures (cache, stack with max, O(1) structures)',
           'Trees and nested structures (Find Leaves, Nested List Weight Sum, LCA)',
           'Graphs: BFS shortest path, topological ordering',
           'Sliding window and two pointers on strings',
           'Follow-ups about complexity, duplicates, huge inputs, and thread-safety'],
   follow='Interviewers push on complexity, edge cases (duplicates, empty, deep nesting), then "how would you make this thread-safe / handle a much larger input".',
   staff='Staff signal is not speed — it is clean interfaces, naming the trade-off, testing out loud, and handling the production follow-up.',
   practice=['Topological sort with cycle reporting and parallel waves', 'LRU and LFU from scratch, then thread-safe',
             'Nested-structure DFS (both LinkedIn variants)', 'Rolling hash / Rabin-Karp', 'Sliding window templates'],
   conf='B — the recurring set comes from aggregators; the individual 2025–2026 reports are first-hand but thin.'),
 'ai': dict(
   summary='LinkedIn runs a real AI-enabled coding round. Reports agree on the shape: a familiar problem, an AI assistant in the panel, and follow-ups that pivot to concurrency and production. Two platforms are reported — CoderPad with a model picker, and HackerRank with a built-in assistant.',
   themes=['Well-known patterns: caches (LRU/LFU), intervals, structured data processing, debug-and-extend a class',
           'Three-phase arc: debug existing code → add a feature → handle edge cases and scale',
           'You copy AI output in yourself; the AI cannot edit the file for you (CoderPad reports)',
           'Evaluation is about prompt quality, verification, production thinking and communication',
           'Concurrency is the most common pivot: thread-safety, race conditions, synchronisation'],
   follow='"Why did you choose this AI-generated approach over the other options?", "How would you test each change?", "If this went to production, what would you change?"',
   staff='Treat the AI as a junior pair: you set the design, it types. Never paste code you cannot defend line by line.',
   practice=['LRU then LFU-with-rank, AI-assisted, narrating every acceptance decision',
             'Debug-and-extend drills on unfamiliar code', 'Interval manager class', 'Malformed-JSON tolerant parsing',
             'Add thread-safety to something you just wrote, and explain the contention cost'],
   conf='A/B — the round is confirmed by multiple 2026 sources including one first-hand report with exact follow-ups; exact problems vary by interviewer.'),
 'design': dict(
   summary='LinkedIn design rounds skew product-centric (feed, PYMK, jobs, notifications, search, autosuggest) with strong infrastructure variants (rate limiter, job scheduler, Kafka-like queue, inverted index). Staff loops in India reported two design rounds.',
   themes=['Retrieval + ranking systems (autosuggest, PYMK, jobs)',
           'Infrastructure primitives (rate limiter, scheduler, message queue, cache)',
           'Search and indexing at scale (distributed inverted index)',
           'Abuse / malicious traffic filtering',
           'Recent LLD-flavoured prompts (calendar, ranked cache)'],
   follow='Partitioning, consistency, failure modes, caching, storage choice, data modelling, observability, cost, rollout, and ML/ranking trade-offs.',
   staff='They listen for trade-offs stated out loud, blast radius reasoning, and evolution — one report ended early because "all the trade-offs are covered".',
   practice=['Rate limiter (highest recency signal)', 'Job scheduler with exactly-once semantics',
             'Autosuggest/typeahead backend', 'Distributed inverted index', 'Kafka-like log and consumer groups',
             'Abuse interception pipeline'],
   conf='B — several first-hand questions (A) plus aggregator recency labels (B/C). Treat the list as coverage, not prediction.'),
 'hm': dict(
   summary='The manager round mixes career narrative with real scenarios. The two strongest recent signals are career-progression walkthroughs and platform-migration influence at scale — both map directly onto your Isolated Cloud work. India Staff loops also carry a separate craftsmanship round.',
   themes=['Career progression and promotion triggers', 'Getting thousands of teams onto a platform, and handling holdouts',
           'Most complex project led, with security and ownership probing', 'Conflict and disagreement in a critical project',
           'Quality philosophy, code review at scale, mentoring', 'Turnaround scenarios for a neglected legacy system',
           'Why LinkedIn, why now'],
   follow='Expect ownership probes ("your role versus the team"), estimation realism, and "what would you do differently".',
   staff='Down-levelling at LinkedIn is reported to hinge on leadership signal across the manager, craftsmanship and design rounds — scope and influence, not extra technical depth.',
   practice=['Career arc in 3 minutes', 'Migration-at-scale story with holdouts', 'Conflict story where you changed the design',
             'Quality/craftsmanship philosophy with mechanisms', 'Legacy turnaround scenario', 'Why LinkedIn, in your own words'],
   conf='A/B — two first-hand 2026 questions, several 2025 aggregated reports.'),
}

LOOP = dict(
  summary='Reported loops vary by org and year. The pattern across 2025–2026 reports: recruiter screen → technical phone screen → 5–7 onsite rounds.',
  rounds=[('Technical phone screen', '1–2 LeetCode-style problems, 60 min, CoderPad', 'prepf'),
          ('Coding rounds (2–3)', 'Medium-to-hard; India Staff loop reported three', 'taro-in'),
          ('AI-enabled coding', 'CoderPad with model picker, or HackerRank with built-in assistant', 'hi-ai'),
          ('System design (1–2)', 'Product-centric or infrastructure; Staff loops reported two', 'taro-in'),
          ('Craftsmanship', 'Code quality, testing, CI/CD, metrics, reactive systems', 'taro-in'),
          ('Host manager / behavioural', 'Career, projects, conflict, scenarios', 'blind-in'),
          ('Technical communication / collaboration', 'Influence, migration and conflict scenarios', 'exp-exp')],
  notes=['Several 2026 reports mention two interviewers per round, one leading and one shadowing. [exp-exp]',
         'Down-levelling Staff → Senior is discussed often on Blind; LinkedIn Staff is described as L5.5+ and the decision is attributed to leadership signal. [blind-lv]',
         'Both Meta-style and LinkedIn AI rounds offer a practice environment beforehand — ask your recruiter for it. [hi-fmt]'])
