# -*- coding: utf-8 -*-
"""Practice designs. Each design is run interactively: the page asks before it tells."""

DESIGNS = [
 dict(id='ratelimit', title='Design a rate limiter', topic='Infrastructure primitive', prio='p0',
  why='The most recent design prompt found in the research — logged on Exponent as asked about a month ago (≈Aug 2026). Also the question your AI-coding rate-limiting exercise already answers in code.',
  ask=['Who are we limiting — user, API key, tenant, IP, or endpoint?',
       'What happens at the limit: reject with 429, queue, or degrade?',
       'Hard limit or smoothed burst? (Bursty interactive traffic vs steady batch.)',
       'Single region or global? Is a small over-count acceptable for lower latency?',
       'Do we limit requests, or cost (tokens, bytes, CPU)?'],
  fr=['Allow or deny a request against a per-key quota', 'Configurable rules per key/route, changeable without deploy',
      'Report remaining quota and retry-after to the caller', 'Observable: current rate, rejections, top offenders'],
  nfr=['Sub-millisecond added latency at p99 (it is on every request)',
       'Fail open or fail closed — a decision, and for an abuse limiter usually fail open for availability, fail closed for billing',
       'Accuracy tolerance: exact vs approximate under partition',
       'Multi-tenant isolation: one tenant cannot exhaust another\'s budget'],
  scale='Assume 200k requests per second across 40 gateway nodes, 10 million distinct keys, rule changes hourly. 200k × 1 counter op = the whole design problem is coordination, not compute.',
  api='`POST /check {key, cost, route}` → `{allowed, remaining, retryAfterMs}`; rules via a control plane with versioned config; usually embedded as a library in the gateway rather than a network call.',
  data='Per key: bucket state (tokens, lastRefillTs) or a windowed counter. Rules: key pattern → {rate, burst, scope}. Hot keys need their own treatment.',
  arch='''Gateway-embedded limiter with a local token bucket per key, synchronised against a shared store (Redis cluster) on a short interval or by leasing quota slices.

Three designs to compare out loud:
1. **Central Redis counter per request** — exact, simple, adds a network hop and a hard dependency on every request.
2. **Local bucket + periodic sync** — fast, approximate, drifts by at most (rate × sync interval) per node.
3. **Quota leasing**: each node leases a slice of the global budget and renews; exact-ish, resilient, and the one to propose at Staff level.''',
  deep=['**Algorithm choice**: token bucket (bursty, simple, O(1) state) vs sliding-window log (exact, memory-heavy) vs sliding-window counter (good compromise).',
        '**Hot keys**: one key taking 30% of traffic. Shard the counter (key:shardN) and sum, or pin to a dedicated node.',
        '**Clock**: never trust wall clocks across nodes for refill; use monotonic time locally and a lease epoch globally.',
        '**Config propagation**: versioned rules pushed to nodes; a node with stale rules must fail safe and report its version.'],
  fails=['Redis down → fall back to local buckets with conservative limits, and alarm. Say which way you fail and why.',
         'Node restart loses local state → cold start allows a burst; bound it by starting buckets empty.',
         'Network partition → each side enforces its own slice; total may exceed the global limit by the number of partitions.'],
  scaling=['Shard by key hash; scale nodes independently of the store.',
           'Batch counter updates (one round trip per interval, not per request).',
           'Tiered limits: cheap local check first, expensive global check only for keys near their limit.'],
  obs=['Allowed/denied per rule and per tenant', 'p99 added latency', 'Drift between local and global counts',
       'Top-N keys by consumption — this is also your abuse signal'],
  sec=['Key spoofing: the identity must come from an authenticated token, not a header the client sets.',
       'Limits must be enforced server-side; a client-side limiter is a UX feature, not a control.'],
  cost='Redis cluster sized for 200k ops/s is the dominant cost; local buckets with 1-second sync cut that by orders of magnitude. Give the arithmetic.',
  trade=[('Exactness', 'Central counter is exact but adds latency and a dependency'),
         ('Availability', 'Local buckets survive a store outage but can over-admit'),
         ('Complexity', 'Leasing is the best behaviour and the most code — justify it with the traffic numbers')],
  evolve='Start with a central counter (correct, simple), measure, then move to leasing when latency or the dependency hurts. Rules engine first-class from day one, because limits change far more often than code.',
  senior='"Token bucket in Redis, 429 when the bucket is empty."',
  staff='"On every request means the limiter is now a dependency of everything, so I would embed it, lease quota, and define the failure mode explicitly: fail open for abuse limiting, fail closed for billing. I would also expect one key to be 30% of traffic and shard its counter."'),

 dict(id='scheduler', title='Design a distributed job scheduler', topic='Infrastructure', prio='p0',
  why='Reported first-hand at LinkedIn (Senior SWE Infrastructure, 30 Sep 2025). The interviewer ended the round saying all the trade-offs were covered — lead with trade-offs.',
  ask=['One-shot jobs, cron-style recurring, or both?', 'Delivery semantics: at-least-once or effectively-once?',
       'What is the acceptable firing skew — seconds or minutes?', 'Who executes: our workers, or a callback to the owning service?',
       'What happens to jobs missed during an outage — run late, or skip?'],
  fr=['Schedule a job for time T, or on a recurrence', 'Cancel and reschedule', 'Execute within the skew budget',
      'Retry failures with a policy', 'Expose job status and history'],
  nfr=['No lost jobs (durability beats latency)', 'Firing skew p99 under a few seconds',
       'Horizontal scale to millions of pending jobs', 'Tenant isolation: one noisy tenant cannot delay others'],
  scale='10 million pending jobs, 5k firings per second at peak, spiky on the hour. The hour boundary is the whole problem: 60% of daily jobs fire in 1% of the time.',
  api='`POST /jobs {runAt|cron, payload, idempotencyKey, retryPolicy}` → jobId; `DELETE /jobs/{id}`; `GET /jobs/{id}`.',
  data='Durable store partitioned by time bucket: (bucketMinute, shard) → jobs. Secondary index by jobId for cancel/status. A lease table (or a lease column) for in-flight ownership.',
  arch='''Writer API → durable store (partitioned by minute bucket and shard) → a set of dispatcher nodes, each owning shards by consistent hashing with a lease → due jobs published to a queue → workers execute with idempotency keys → results and retries written back.

Say why *not* a single timer wheel in one process: it does not survive restarts and cannot scale past one machine\'s clock.''',
  deep=['**The thundering herd on the hour**: jitter jobs within their minute, and pre-fetch the next bucket early.',
        '**Exactly-once effects**: at-least-once delivery plus an idempotency key checked by the executor. Say plainly that exactly-once delivery is not achievable; exactly-once *effects* are.',
        '**Ownership**: leases with fencing tokens so a paused dispatcher cannot double-fire after a GC pause.',
        '**Missed windows**: on recovery, decide per job class — fire late, or skip with a "missed" event. Make it a policy field, not a global rule.',
        '**Long jobs**: the scheduler triggers, it does not execute. Keep execution in a worker pool with its own back-pressure.'],
  fails=['Dispatcher dies → lease expires, another node picks up the shard; jobs may fire twice, hence idempotency.',
         'Store slow → dispatch lag grows; shed by priority, and alarm on lag rather than on errors.',
         'Poison job that always fails → retry with backoff, then dead-letter with an alert.',
         'Clock skew between dispatchers → use the store\'s time as the authority.'],
  scaling=['Partition by (time bucket, shard) so hot minutes spread across nodes.',
           'Separate the read path (status) from the dispatch path.',
           'Priority lanes so a bulk backfill cannot starve interactive jobs.'],
  obs=['Dispatch lag (now − scheduled time) at p50/p99 — the single most important metric',
       'Firings per second, retries, dead-letters', 'Lease churn (a proxy for node instability)',
       'Per-tenant queue depth'],
  sec=['Payloads may contain secrets — encrypt at rest and redact in logs.',
       'Authorisation on cancel/status: a tenant may only touch its own jobs.'],
  cost='Storage is cheap; the dispatcher fleet is sized for the peak minute, not the average. Point that out and propose smoothing.',
  trade=[('Durability vs latency', 'Write to durable storage before acknowledging — slower writes, no lost jobs'),
         ('Exactly-once', 'Idempotency at the executor instead of impossible delivery guarantees'),
         ('Skew', 'Tighter skew costs more pre-fetching and more nodes idling at the boundary')],
  evolve='Phase 1: single-region, at-least-once, minute granularity. Phase 2: priority lanes and per-tenant isolation. Phase 3: multi-region with a regional owner per job to avoid cross-region double firing.',
  senior='"A cron table and workers polling for due jobs."',
  staff='"Polling is fine until the hour boundary, where 60% of the load lands. I would partition by minute bucket, lease shards with fencing tokens, and treat idempotency at the executor as the real delivery guarantee. The metric I would page on is dispatch lag, not error rate."'),

 dict(id='autosuggest', title='Design autosuggest / typeahead for person search', topic='Search · Serving', prio='p0',
  why='A 2026 candidate reported "design the backend for an autosuggest feature"; Exponent also lists "typeahead autocomplete for person search in LinkedIn". Two independent hits makes this high-signal.',
  ask=['Prefix matching only, or fuzzy and mid-word?', 'Personalised (my network first) or global popularity?',
       'Latency budget — 50 ms? 100 ms?', 'How fresh must new members be: seconds, or next index build?',
       'How many suggestions, and do we need to explain them?'],
  fr=['Return ranked suggestions for a prefix as the user types', 'Personalise by the searcher\'s network and history',
      'Handle typos', 'Respect privacy settings and blocks'],
  nfr=['p99 under ~100 ms end to end, including the network', 'Very high read rate, low write rate',
       'Graceful degradation: a generic ranking is better than no suggestions', 'Index freshness within minutes'],
  scale='1 billion members, 100k queries per second at peak, average 4 keystrokes per search. Every keystroke is a request unless you debounce — say that first.',
  api='`GET /suggest?q=ric&limit=10` → suggestions with ids, display text, and a ranking trace id for experimentation.',
  data='Inverted index / FST keyed by prefix → candidate ids with static scores. A separate feature store for personalisation (connection degree, recent interactions).',
  arch='''Two-stage, as with all LinkedIn serving systems:
1. **Candidate generation** — prefix lookup in an in-memory trie/FST shard, returning a few hundred candidates by static score (popularity, completeness).
2. **Ranking** — rerank the shortlist with personalisation features (degree of connection, shared company, recency) in a lightweight model.

Index build is offline (batch), pushed to serving nodes as immutable segments; a small real-time layer holds the last few minutes of changes.''',
  deep=['**Sharding**: by prefix range or by member hash? Prefix range gives single-shard queries but hot shards ("a", "s"); member hash needs scatter-gather. Recommend prefix range with hot-shard splitting.',
        '**Caching**: the top prefixes dominate — cache per (prefix, viewer-segment), not per (prefix, viewer), or hit rate collapses.',
        '**Typos**: edit-distance-1 expansion at query time, or a phonetic key in the index. Budget it: fuzzy is a cost multiplier.',
        '**Personalisation cost**: fetching features per candidate is the latency risk — keep features denormalised and co-located with the index.',
        '**Debouncing**: client-side 80–120 ms debounce cuts traffic by ~60% and costs nothing. Say it early; it is the cheapest win.'],
  fails=['Ranking service down → return candidate-generation order (degraded but useful).',
         'A shard down → serve from a replica; if none, return partial results and mark them.',
         'Index build broken → keep serving the previous segment; never push an unvalidated index.'],
  scaling=['Replicate read-only segments widely; reads scale linearly.',
           'Split hot prefix shards by a second key.', 'Cache at the edge for anonymous or logged-out traffic.'],
  obs=['p99 by stage (lookup vs rank)', 'Click-through on suggestions (the real quality metric)',
       'Zero-result rate per prefix length', 'Index age on each serving node'],
  sec=['Never suggest members the viewer is not allowed to see (blocks, private profiles) — filter inside candidate generation.',
       'Typeahead can leak existence of accounts; rate-limit and avoid confirming private identities.'],
  cost='Memory-resident index across 1B members is the cost driver: compress with an FST, store only ids plus a small score, and fetch display data from a separate store.',
  trade=[('Freshness vs simplicity', 'Immutable segments are simple and fast; the real-time layer exists only because "I signed up and cannot find myself" is unacceptable'),
         ('Personalisation vs latency', 'Every feature lookup is latency; denormalise or drop the feature'),
         ('Fuzzy vs cost', 'Typo tolerance multiplies candidates — gate it by prefix length')],
  evolve='Start global-popularity-only (ship in weeks), add network personalisation, then add the real-time layer, then typo tolerance. Each step is independently measurable by click-through.',
  senior='"A trie in memory, return the top ten by popularity."',
  staff='"The trie is the easy half. The decisions are sharding (prefix range with hot-shard splitting), the two-stage retrieval/ranking split so personalisation does not blow the latency budget, and the freshness layer. I would also debounce on the client, which removes more than half the load for free."'),

 dict(id='index', title='Design a distributed inverted index (Elasticsearch-like)', topic='Search · Storage', prio='p0',
  why='Reported first-hand by a Staff candidate in India (May 2025) — the closest data point to your own loop.',
  ask=['Near-real-time indexing, or batch is fine?', 'Query types: boolean, phrase, ranked, faceted?',
       'Update rate versus query rate?', 'Are deletes and updates frequent (they are the hard part)?',
       'Consistency expectation: can a write be invisible for a second?'],
  fr=['Index documents with fields', 'Query by terms with boolean and phrase operators, ranked by relevance',
      'Update and delete documents', 'Return results with scores and pagination'],
  nfr=['Query p99 in tens of milliseconds', 'Index visible within seconds (NRT)',
       'Durable: no acknowledged document is lost', 'Scale horizontally on both index size and query rate'],
  scale='10 billion documents, 50k queries per second, 20k document updates per second. Index size dominates: plan shards by memory, not by document count alone.',
  api='`PUT /doc/{id}`, `DELETE /doc/{id}`, `POST /search {query, filters, from, size}` → hits with scores.',
  data='Segment files: term dictionary → postings list (doc ids, positions, frequencies), plus a doc-values column store for sorting and faceting, and a tombstone set for deletes.',
  arch='''Write path: document → routed by hash to a shard → appended to an in-memory buffer and a durable translog → periodically flushed into an immutable segment → segments merged in the background.

Read path: query → coordinator → fan-out to one replica of every shard → each returns its top-k → coordinator merges → fetch stored fields for the final k only (fetch phase separate from the query phase).''',
  deep=['**Immutable segments**: why they exist (lock-free reads, cacheable, cheap merges) and what they cost (deletes are tombstones, space amplification until merge).',
        '**NRT visibility**: refresh interval controls the freshness/throughput trade — a one-second refresh is a choice, not a law.',
        '**Scoring**: TF-IDF/BM25 computed per shard means shard-local statistics; global scoring needs a two-phase query (DFS) — a real trade-off worth naming.',
        '**Deep pagination**: from=10000 forces every shard to return 10k — use search-after with a sort key instead.',
        '**Merge policy**: merges are the hidden cost centre; they compete with indexing for IO.'],
  fails=['Node loss → replica promotion; unacknowledged writes in the translog replay.',
         'Hot shard (one huge tenant) → route that tenant to dedicated shards.',
         'Merge storm → back-pressure indexing, never queries.',
         'Query of death (expensive regex/wildcard) → timeouts per shard plus a query cost budget.'],
  scaling=['Shard count is fixed at creation in most designs — over-shard modestly, and plan reindexing as the resharding path.',
           'Replicas scale reads; shards scale writes and index size.',
           'Separate hot and cold tiers by time for log-like data.'],
  obs=['Query latency split into query and fetch phases', 'Indexing lag and refresh time',
       'Segment count and merge backlog', 'Per-shard skew — the early warning for a hot tenant'],
  sec=['Per-tenant filtering must be applied inside the query, not after, and enforced by the platform rather than every caller — this is exactly the Isolated Cloud lesson.',
       'Field-level access control for sensitive fields.'],
  cost='Memory for the term dictionary and doc values dominates. Compression and tiering are the levers; say roughly what a billion small documents costs in RAM.',
  trade=[('Freshness vs throughput', 'Shorter refresh means more segments and more merging'),
         ('Global scoring vs latency', 'Two-phase scoring is more accurate and a round trip slower'),
         ('Shard size', 'Big shards recover slowly; small shards multiply per-query fan-out cost')],
  evolve='Start with one index and generous shard sizing, add replicas for read scale, then hot/cold tiering, then per-tenant dedicated shards for the largest tenants — the same tiering instinct as your platform work.',
  senior='"Use Elasticsearch: shard it and add replicas."',
  staff='"The interesting parts are the immutable-segment model and the consequences: deletes as tombstones, merge IO competing with indexing, shard-local scoring, and deep pagination. I would also route the largest tenants onto dedicated shards, because one hot tenant otherwise sets the latency for everyone."'),

 dict(id='queue', title='Design a Kafka-like distributed message queue', topic='Messaging', prio='p0',
  why='Reported in a LinkedIn Staff experience (Jun 2025). LinkedIn built Kafka, so expect internals, not name-dropping.',
  ask=['Ordering: per partition or global?', 'Delivery: at-least-once, at-most-once, or effectively-once?',
       'Retention: time, size, or compacted by key?', 'Consumer model: groups with rebalancing, or explicit assignment?',
       'Throughput and message size?'],
  fr=['Publish to a topic partition', 'Consume with tracked offsets', 'Replay from an offset or timestamp',
      'Consumer groups with automatic rebalancing'],
  nfr=['Millions of messages per second, sequential IO-bound', 'Durability through replication with a configurable acknowledgement level',
      'Ordering guaranteed within a partition', 'Bounded end-to-end latency at p99'],
  scale='1 million messages per second, average 1 KB → 1 GB/s ingress, ×3 replication = 3 GB/s of disk writes. That arithmetic drives the whole design.',
  api='`produce(topic, partitionKey, payload, acks)`; `fetch(topic, partition, offset, maxBytes)`; `commitOffset(group, partition, offset)`.',
  data='Append-only log per partition, split into segment files with a sparse offset index; offsets are monotonic per partition; consumer offsets stored in an internal compacted topic.',
  arch='''Producers hash the key to a partition → append to the leader\'s log → followers replicate → the in-sync replica set (ISR) defines durability → consumers read sequentially from their offset, with the page cache doing most of the work.

Zero-copy transfer from page cache to socket is why this design is fast; say it, because it explains why the broker does so little per message.''',
  deep=['**ISR and acks**: acks=all means the write is acknowledged when every in-sync replica has it; shrinking ISR trades durability for availability. This is the core correctness discussion.',
        '**Ordering**: only within a partition; a keyed partitioner is what gives per-entity ordering. Repartitioning breaks it — call that out.',
        '**Consumer groups**: rebalancing is the operational pain (stop-the-world assignment, duplicate processing after a rebalance). Mention sticky/incremental rebalancing.',
        '**Effectively-once**: idempotent producer (sequence numbers per partition) plus transactional commits, or idempotent consumers. Do not say "exactly once" without qualifying it.',
        '**Compaction**: key-compacted topics as a changelog / state store — this is how stream processors recover state.'],
  fails=['Leader failure → controller elects a new leader from the ISR; unreplicated tail is lost if acks were weak.',
         'Slow follower → dropped from ISR; durability quietly weakens. Alarm on ISR size.',
         'Consumer lag growth → back-pressure signal; scale consumers up to the partition count, which is the hard ceiling.',
         'Disk full → broker stops accepting writes; retention policy is a capacity decision.'],
  scaling=['Partitions are the unit of parallelism — choose the count for the eventual consumer parallelism, because increasing it later breaks key ordering.',
           'Tiered storage moves cold segments to object storage, decoupling retention from broker disk.',
           'Separate high-throughput topics onto dedicated brokers.'],
  obs=['Consumer lag per group and partition (the headline metric)', 'ISR size and under-replicated partitions',
       'Produce/fetch latency percentiles', 'Rebalance frequency'],
  sec=['Per-topic ACLs, mTLS between brokers and clients, and encryption at rest for sensitive topics.',
       'A shared cluster is a multi-tenant system: quotas per client id or the noisy neighbour wins.'],
  cost='Disk throughput and retention length dominate. Tiered storage changes the economics; quote the ingress arithmetic and then the retention multiplier.',
  trade=[('Durability vs latency', 'acks=all with a large ISR is slower and safer'),
         ('Partition count', 'More parallelism, more metadata and more rebalancing pain'),
         ('Retention', 'Replayability costs storage — and replay is the feature that makes the log worth having')],
  evolve='Start with a modest partition count and acks=all for critical topics; add tiered storage when retention outgrows disks; introduce quotas the first time a tenant hurts another.',
  senior='"Producers write to topics, consumers read with offsets, replication gives durability."',
  staff='"The design is a log plus the ISR protocol, and the interesting failures are ISR shrink (durability silently weakening), rebalance storms, and the fact that partition count caps consumer parallelism forever. I would size partitions for the consumer parallelism I expect in two years, not today."'),

 dict(id='abuse', title='Design a system that intercepts and denies malicious requests', topic='Trust & safety', prio='p1',
  why='Reported on Blind as a LinkedIn onsite design question (undated, single source — treat as practice, not prediction). It is also the best fit for your platform-and-policy background.',
  ask=['What counts as malicious — credential stuffing, scraping, spam, fraud?',
       'Is blocking synchronous (deny the request) or asynchronous (act after the fact)?',
       'What false-positive rate is acceptable? (Blocking a real member is expensive.)',
       'Who can change rules, and how fast must a new rule take effect?',
       'What signals may we use — privacy and regulatory limits?'],
  fr=['Score every request in line and allow/deny/challenge', 'Rules updatable in minutes without deploy',
      'Feedback loop from confirmed abuse into features', 'Auditable decisions with a reason per block'],
  nfr=['Single-digit millisecond added latency at p99', 'Fail open (availability) with a conservative static ruleset as fallback',
       'Rule change propagation within minutes', 'Explainability: every block must be reviewable'],
  scale='Tens of thousands of requests per second at the edge, features from the last minute, hours and days; most requests are benign, so optimise for the fast allow path.',
  api='Edge middleware: `evaluate(request, identity, deviceFingerprint)` → `{allow|challenge|deny, reasonCode, ruleVersion}`.',
  data='Feature store keyed by (ip, account, device, fingerprint) with counters over tumbling windows; rules as versioned config; labels from confirmed abuse cases.',
  arch='''Edge filter (cheap, static rules and reputation) → in-line scorer (features from a low-latency store plus a small model) → policy engine (allow / challenge / deny, with reason codes) → async pipeline (stream of events → aggregation → feature store → offline training and rule mining) → feedback from confirmed cases.

Keep the synchronous path thin: lookups plus a small model. Everything expensive happens asynchronously and lands in the feature store for the next request.''',
  deep=['**Two-speed architecture**: in-line decisions must be milliseconds; detection can be seconds behind. Say which signals live where.',
        '**Challenge instead of block**: a captcha or step-up auth converts a false positive into friction rather than a lockout.',
        '**Attackers adapt**: any static rule decays. The system must support fast rule iteration and shadow mode (score, do not enforce) to measure before enforcing.',
        '**Sharing without leaking**: features are behavioural aggregates, not raw personal data. State the privacy boundary explicitly.',
        '**Blast radius**: a bad rule can deny everyone. Staged rollout by percentage, automatic rollback on a spike in denials — the same waves-and-gates instinct as a platform rollout.'],
  fails=['Feature store slow → fall back to static rules and allow (or challenge) rather than deny.',
         'Model service down → rules-only mode; announce degraded detection.',
         'Bad rule deployed → automatic rollback triggered by the denial-rate alarm.',
         'Attack during a deploy → freeze rule changes during incidents, but keep an emergency path with two-person approval.'],
  scaling=['Aggregate counters with sketches (count-min, HyperLogLog) instead of exact counts.',
           'Partition feature lookups by key; co-locate with the edge region.',
           'Sample benign traffic for the async pipeline; keep 100% of suspicious traffic.'],
  obs=['Denial rate by rule and by segment', 'False-positive proxy: appeals and support tickets',
       'Rule version live on each node', 'Detection lag between abuse start and rule firing'],
  sec=['The system itself is a target: rule config needs strong authorisation and an audit trail.',
       'Never log raw credentials or full payloads; hash and redact.'],
  cost='In-line lookups dominate at scale; sketches and edge caching are the levers. Async processing is elastic and can be throttled.',
  trade=[('False positives vs coverage', 'Every point of recall costs real members; challenge is the middle path'),
         ('Latency vs sophistication', 'Better models need more features and more time'),
         ('Transparency vs evasion', 'Detailed reasons help support teams and also help attackers tune')],
  evolve='Phase 1: static rules and reputation at the edge with shadow mode. Phase 2: features plus a small in-line model. Phase 3: feedback loop and automated rule mining. Never enforce a new signal before shadow-measuring it.',
  senior='"Rate limit by IP and block the bad ones."',
  staff='"IPs are cheap for attackers and shared by real members, so the interesting design is two-speed: a thin in-line decision with reason codes, and an async pipeline that learns. The riskiest component is the rule rollout, so it gets staged deployment and automatic rollback — a bad rule is an outage you caused."'),

 dict(id='notify', title='Design a member-first notification system', topic='Product platform', prio='p1',
  why='A recurring LinkedIn design theme across guides (aggregation, per-member rate limiting, channel preferences). Multi-channel delivery with per-member limits is also close to your platform work.',
  ask=['Which channels: in-app, push, email, SMS?', 'Who decides what is worth sending — the producing team, or a central policy?',
       'What are the per-member frequency caps?', 'Is ordering or deduplication required across channels?',
       'How fast must a notification arrive — seconds or minutes?'],
  fr=['Accept notification requests from many producing services', 'Resolve member preferences and channel eligibility',
      'Aggregate related events ("3 people viewed your profile")', 'Deliver per channel with retries and receipts'],
  nfr=['Never spam: hard per-member caps enforced centrally', 'Deliver time-sensitive notifications within seconds',
       'Isolation: one producing service cannot starve others', 'Auditable: why did this member receive this?'],
  scale='1 billion members, 10 billion candidate events per day, of which only a fraction should ever be sent. The system\'s job is mostly *suppression*.',
  api='`POST /notify {memberId, type, payload, priority, dedupeKey, expiry}` → accepted/suppressed with a reason.',
  data='Per-member: preferences, channel tokens, recent delivery history (for caps and dedupe). Per type: policy, aggregation window, priority.',
  arch='''Producers → ingestion queue → policy and preference resolution → aggregation window (buffer related events per member/type) → per-channel dispatchers → delivery receipts → feedback (opens, dismissals, unsubscribes) into relevance scoring.

The central point to make: this is a *platform*, so policy lives here rather than in every producing team — the same argument you made for isolation being a platform capability.''',
  deep=['**Aggregation**: time window per type, keyed by (member, type). Flush on window close or on a count threshold.',
        '**Frequency capping**: a token bucket per member per channel — your rate limiter design, reused.',
        '**Priority**: security alerts bypass caps; growth notifications never do. That table is a product decision you should force into the open.',
        '**Dedupe**: the same event from two producers, or across channels (do not push and email the same thing within minutes).',
        '**Relevance feedback**: dismissals and unsubscribes must reduce future sends, or the system slowly trains members to ignore it.'],
  fails=['Push provider down → queue with expiry; drop rather than deliver a stale "meeting in 5 minutes" an hour later.',
         'Preference store unavailable → fail closed (do not send), because the cost of a wrong send is worse than a late one.',
         'Producer floods the ingress → per-producer quotas, with visible back-pressure.',
         'Duplicate delivery after a retry → dedupe key with a delivery record.'],
  scaling=['Partition by member id everywhere — caps, aggregation and delivery all key on the member.',
           'Separate the time-sensitive lane from the batch lane.',
           'Shard delivery by channel provider to isolate provider outages.'],
  obs=['Sent vs suppressed by reason (the most useful dashboard)', 'Per-member send distribution — watch the tail, not the mean',
       'Delivery latency by channel', 'Unsubscribe and dismissal rates by type'],
  sec=['Notification content leaks information — never include private details in a lock-screen push.',
       'Unsubscribe must be honoured everywhere immediately; it is often a legal requirement.'],
  cost='SMS and email have hard per-message costs, so suppression is a cost lever as well as a member-experience lever. Quantify it.',
  trade=[('Central policy vs team autonomy', 'Teams lose control of when their notification fires; in exchange members stay subscribed'),
         ('Aggregation delay vs immediacy', 'Longer windows mean fewer, better notifications and slower delivery'),
         ('Fail closed on preferences', 'Fewer sends during an outage, no policy violations')],
  evolve='Start with per-type policies and hard caps; add aggregation; then relevance scoring with feedback. Keep a kill switch per notification type — you will need it.',
  senior='"A queue per channel, workers send the notifications."',
  staff='"Most of the value is in what we do not send. The platform owns caps, dedupe and preferences centrally, because a hundred producing teams will not each implement them correctly — and the failure is invisible until members disable notifications entirely. Security alerts are the only class that bypasses caps."'),

 dict(id='pymk', title='Design People You May Know (PYMK)', topic='Graph · Recommendations', prio='p1',
  why='A canonical LinkedIn design across guides: billion-node graph, triangle closing, precompute-versus-online, retrieval and ranking.',
  ask=['What is the success metric — connections made, or accepted invitations?',
       'How fresh must recommendations be after a new connection?',
       'Do we serve on the profile page, a dedicated tab, or notifications (different latency budgets)?',
       'Any hard exclusions — blocked members, declined invitations, privacy settings?'],
  fr=['Return ranked candidate people for a member', 'Explain why ("you both know X")',
      'Exclude existing connections, blocks and recently dismissed', 'Learn from accepts and dismisses'],
  nfr=['Serving p99 under ~100 ms', 'Refresh within hours for most members, minutes after a major event (new job, new connection)',
       'Scale: 1B members, average hundreds of connections, so second-degree sets are enormous'],
  scale='1 billion members × ~500 connections = 500 billion edges. A naive second-degree expansion for a hub member touches tens of millions of candidates — which is exactly why this is a two-stage problem.',
  api='`GET /pymk?memberId=&limit=20` → candidates with scores and explanation tokens.',
  data='Adjacency lists partitioned by member; precomputed candidate sets with scores; feature store for ranking (shared connections, company, school, interactions).',
  arch='''Offline: batch job over the graph computes candidate sets (friends-of-friends with counts, plus affiliation-based candidates), scores them cheaply, and writes the top few hundred per member to a serving store.

Online: fetch the precomputed set, filter (already connected, dismissed, blocked), rerank with fresh features, and explain.

Incremental: a streaming path updates candidates for members whose graph just changed, so a new connection changes recommendations in minutes rather than at the next batch.''',
  deep=['**Hub members**: someone with 30,000 connections makes second-degree expansion explode. Cap the expansion, sample edges, or exclude hubs from candidate generation — and say why that is acceptable.',
        '**Triangle closing vs affiliations**: shared connections are the strongest signal, but new members have no edges — cold start needs company, school and contacts imported.',
        '**Precompute vs online**: precompute is cheap to serve and stale; online is fresh and expensive. The hybrid (precomputed candidates, online rerank and filter) is the answer worth defending.',
        '**Feedback**: dismissals must suppress the candidate for a long time; accepted invitations change the graph and must trigger a refresh.'],
  fails=['Batch job fails → serve yesterday\'s candidates (degraded, acceptable).',
         'Feature store down → serve the precomputed order without reranking.',
         'Graph update lag → a member sees someone they just connected with; filter at serve time against the live connection list to make this impossible.'],
  scaling=['Partition the graph by member and keep adjacency lists compact (ids only).',
           'Sample or cap edges for hubs.', 'Cache per-member results with a short TTL, invalidated on connection events.'],
  obs=['Invitation acceptance rate (the real metric)', 'Coverage: members with fewer than k candidates',
       'Staleness distribution', 'Dismissal rate by explanation type'],
  sec=['Privacy: never reveal a connection the viewer is not entitled to see, and be careful that explanations do not leak private relationships.',
       'Blocked and reported members must be excluded at serve time, not just in the batch.'],
  cost='The batch graph job is the dominant cost; incremental updates for active members are far cheaper than a full recompute. Say when you would run each.',
  trade=[('Precompute vs freshness', 'Hybrid: stale candidates, fresh filtering and ranking'),
         ('Hub handling', 'Sampling loses some recall and saves the system'),
         ('Explanations', 'They lift acceptance and constrain what you are allowed to use as a feature')],
  evolve='Phase 1: batch friend-of-friend with simple scoring. Phase 2: online rerank with features. Phase 3: streaming updates for members whose graph changes. Phase 4: model-based ranking with feedback.',
  senior='"Find friends of friends and sort by the number of shared connections."',
  staff='"That works until a hub member, where the second-degree set is tens of millions. So: precompute candidates offline with sampling for hubs, keep filtering and ranking online because the graph changes under us, and treat the explanation as part of the product because it is what moves acceptance rate."'),
]

# catalogue of everything else, linking to the existing 26-design guide
CATALOGUE = [
 ('News feed / activity stream', 'Fan-out on write vs read, ranking, dedupe', '../../index.html#design-twitter'),
 ('Messaging / chat', 'Delivery receipts, ordering, presence, offline queues', '../../index.html#design-whatsapp'),
 ('Distributed cache', 'Consistent hashing, eviction, hot keys', '../../index.html#design-cache'),
 ('Typeahead (guide version)', 'Trie, ranking, index build', '../../index.html#design-typeahead'),
 ('Metrics and logging platform', 'Ingest, aggregation, retention tiers', '../../index.html#design-metrics'),
 ('Web crawler', 'Politeness, frontier partitioning, dedupe', '../../index.html#design-crawler'),
 ('Object storage / file sync', 'Chunking, dedupe, conflict resolution', '../../index.html#design-drive'),
 ('Video platform', 'Transcoding pipeline, CDN, adaptive bitrate', '../../index.html#design-youtube'),
 ('Ride hailing / geospatial', 'H3 indexing, matching, real-time location', '../../index.html#design-uber'),
 ('Payments / billing', 'Idempotency, ledgers, reconciliation, exactly-once effects', '../../index.html#design-adbilling'),
 ('Booking under contention', 'Invariant on one row, holds and expiry', '../../index.html#design-booking'),
 ('Collaborative editing', 'CRDTs vs OT, presence, offline', '../../index.html#design-collab'),
 ('Denylist / IP blocking', 'Bloom filters, propagation, false positives', '../../index.html#design-denylist'),
 ('Fleet upgrade (5,000 servers)', 'Waves, canaries, rollback — mirrors your platform rollout story', '../../index.html#design-fleet-upgrade'),
 ('ML inference serving', 'Batching, autoscaling, model versioning', '../../index.html#design-ml-inference'),
 ('RAG / LLM system', 'Retrieval, grounding, evaluation, cost', '../../index.html#design-rag'),
 ('Distributed job queue', 'Visibility timeouts, dead letters, priority', '../../index.html#design-jobs'),
 ('Key-value store', 'Quorums, anti-entropy, consistent hashing', '../../index.html#design-kv'),
]
